Retain the last saved filename after saving a file
Ultimaker/Cura pull request #10328
Opened 2021-08-23 15:09 UTC by konskarm

Cura was not retaining the last saved filename selected by the user after they were saving their file. This PR fixes that by making sure that the filename selected by the user in the save file dialog will update the name of the workspace (project) all around Cura.

**Note:** The stored filename is forgotten when the user loads another project file, creates a new project (Ctrl+N) or clears the buildplate (Ctrl+D).

Requires https://github.com/Ultimaker/Uranium/pull/728

CURA-8358

2021-08-24 10:42 UTC, nallath approved these changes

2021-08-25 11:37 UTC, Ghostkeeper requested changes

2021-09-01 14:27 UTC, nallath approved these changes

2021-09-02 07:30 UTC, nallath approved these changes

2021-09-02 07:54 UTC, merged

2021-09-10 14:33 UTC, Ghostkeeper commented on plugins/DigitalLibrary/src/DigitalFactoryController.py
> +        self.uploadStarted.emit(filename if "3mf" in formats else None)
This change causes DigitalLibrary to require a higher API version number, meaning it's no longer backwards compatible with Cura 4.9.

2021-09-10 14:33 UTC, Ghostkeeper commented on plugins/DigitalLibrary/src/DigitalFactoryOutputDevice.py
> +            self.setLastOutputName(new_name)  # On saving, the user can change the name, this should propagate.
This change causes DigitalLibrary to require a higher API version number, meaning it's no longer backwards compatible with Cura 4.9.