Add quality profiles for Weedo X40
Ultimaker/Cura pull request #10345
Opened 2021-08-27 16:24 UTC by x40-Community

Quality profiles for Weedo X40 printer

2021-09-06 07:56 UTC, nallath requested changes
I've checked some of the settings at random and found quite a few cases where settings were overridden without it needing to be like that. 

Please double check if the changes that you make are actually needed. This will make it a lot easier to maintain the profiles in the future.

2021-09-06 07:56 UTC, nallath commented on resources/intent/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Extra_Fine_Engineering.inst.cfg
> +material = Extrudr_GreenTECPro_Black_175
So the engineering intent is only there for the black material? That seems a bit weird. 

Ah. I see the issue now; the original profiles were also only there for black material, which is also weird...

2021-09-06 07:56 UTC, nallath commented on resources/intent/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Extra_Fine_Engineering.inst.cfg
> +speed_print = 30
No need to re set the speed. The quality profile already sets it to 30

2021-09-06 07:56 UTC, nallath commented on resources/intent/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Extra_Fine_Engineering.inst.cfg
> +top_bottom_thickness = =wall_thickness
It seems that you're setting this for every intent. Shouldn't it be in the quality instead? (or should it be set like this for all intents except for default?)

2021-09-06 07:56 UTC, nallath commented on resources/intent/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Fine_Engineering.inst.cfg
> +wall_line_width_x = =line_width
This is already the default in fdmprinter. No need to overide it again

2021-09-06 07:56 UTC, nallath commented on resources/intent/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Red_Draft_Draft.inst.cfg
> +material = Extrudr_GreenTECPro_Black_175
The ID of the profile says _greentecpro_red, but the material is greentecpro_black

I think it's better to just add greentecpro as a generic material and let all of them reference to that

2021-09-06 07:56 UTC, nallath commented on resources/quality/weedo_x40/Extrudr/weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Draft.inst.cfg
> +support_z_distance = 0.2
Why override this again? The definition sets it to  "layer_height if layer_height >= 0.16 else layer_height*2"

2021-11-18 14:10 UTC, Ghostkeeper commented
There are conflicts still, but by your attempts to resolve those conflicts I think we'll know how to resolve those.

2021-11-18 14:20 UTC, Ghostkeeper commented
To be merged together with this PR: https://github.com/Ultimaker/fdm_materials/pull/183

2021-11-18 15:24 UTC, Ghostkeeper commented
This PR has quite a big maintenance problem, and I'm not really sure how to deal with it here. It's a lot of work to fix something like this or even to point out where the problem specifically lies. The root of the problem is performance here: This PR adds 1100 profiles, but only 24 unique sets of settings. Most of them are duplicates. This is a result of two issues that need to be addressed:

Duplicate profiles for colours
----
This is one set of profiles which are all duplicates:
```
weedo_x40_0.4_Material4Print_PETG_Black_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Black_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightgreen_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightgreen_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightorange_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightorange_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightred_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightred_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Dustygrey_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Dustygrey_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Greyaluminium_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Greyaluminium_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Irongrey_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Irongrey_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Purered_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Purered_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Signalblue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Signalblue_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Skyblue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Skyblue_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Trafficyellow_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Trafficyellow_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentblack_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentblack_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentblue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentblue_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentgreen_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentgreen_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentred_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentyellow_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparent_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparent_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_White_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_White_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Anthracite_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Anthracite_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Black_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Black_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Blue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Blue_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brightorange_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brightred_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brightred_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brown_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brown_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Dustygrey_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Dustygrey_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Green_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentred_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentyellow_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Brightorange_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Greyaluminium_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Greyaluminium_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Irongrey_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Irongrey_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Ivory_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Ivory_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Magenta_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Magenta_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Nature_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Nature_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Pearlblue_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Perlgold_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Perlgold_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Purered_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Purered_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Purple_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Purple_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Signalblue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Trafficyellow_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Trafficyellow_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_White_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_White_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Yellowgreen_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Yellowgreen_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Green_Normal_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Pearlblue_Fine_Engineering.inst.cfg
weedo_x40_0.4_Material4Print_PLA_Signalblue_Normal_Engineering.inst.cfg
```
All with the following overrides:
```
acceleration_enabled=True
infill_sparse_density=30
jerk_enabled=True
outer_inset_first=True
top_bottom_thickness==wall_thickness
wall_thickness==line_width * 3
xy_offset==-layer_height * 0.2
```

This indicates that there are unique profiles for every colour of filament. However this is unnecessary. Profiles match on materials with a three-tier system:
* If there are any quality/intent profiles specific to the current material the list of those quality profiles is shown.
* Otherwise, it will show the list of all quality/intent profiles specific to a material of the same *material type* as the current material.
* If there are none of those, it will use an empty quality/intent profile.

As such, you don't need to make a unique profile for each colour, only a unique profile for each material type. You can still make a profile for a specific colour if that material needs different settings due to its pigment or something.

Improper material types
----
This is a second set of duplicate profiles:
```
weedo_x40_0.4_Extrudr_GreenTECPro_Anthracit_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_Black_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_Blue_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_Nature_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_Red_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_Silver_Normal_Visual.inst.cfg
weedo_x40_0.4_Extrudr_GreenTECPro_White_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Transparentblack_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Black_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightgreen_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightorange_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Dustygrey_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Greyaluminium_Normal_Visual.inst.cfg
weedo_x40_0.4_Material4Print_PETG_Brightred_Normal_Visual.inst.cfg
weedo_x4 [...]

2021-12-20 16:09 UTC, closed without merging