cremaker def files added
Ultimaker/Cura pull request #10409
Opened 2021-09-08 02:00 UTC by hyu7000

cremaker M1, M2, S1, extruder, 200 bed, 220 bed obj file added

2021-09-13 04:25 UTC, hyu7000 commented
hello. 

some value is changed. could you check it out?

2021-09-13 09:08 UTC, nallath commented
Sorry, CI is still failing.

2021-09-13 11:16 UTC, hyu7000 commented
some "default_value" was changed to "value".

If this keep failing, Could you tell me if there's anything i'm missing?

2021-09-21 14:34 UTC, konskarm commented
Hi @hyu7000. Thank you for your contribution. Could you please provide links to the product pages of these printers? I cannot find their specifications anywhere.

2021-09-21 16:20 UTC, hyu7000 commented
https://www.facebook.com/cremaker/
cremaker's facebook is here. 

https://cafe.naver.com/cremaker
this link is korean user web comunity of cremaker

it's korean's company.

do you need any other imformation?

2021-09-23 02:07 UTC, hyu7000 commented
https://smartstore.naver.com/cremaker/products/5311082072

Additionally, this is shop link

2021-09-28 14:48 UTC, konskarm requested changes
Some changes are needed for this to work. Currently, Cura crashes when adding a Cremaker printer because of those issues.

2021-09-28 14:48 UTC, konskarm commented on resources/definitions/cremaker_common.def.json
> +    "adhesion_type": { "value": "skirt" },
```suggestion
    "adhesion_type": { "value": "'skirt'" },
```

2021-09-28 14:48 UTC, konskarm commented on resources/definitions/cremaker_common.def.json
> +    "retraction_combing": { "value": "Within Infill" },
```suggestion
    "retraction_combing": { "value": "'infill'" },
```

2021-09-28 14:48 UTC, konskarm commented on resources/definitions/cremaker_common.def.json
> +    "machine_center_is_zero": { "default_value": false },
This is already inherited as `false` from the `fdmprinter.def.json` so no need to include it here.
```suggestion
```

2021-09-30 04:11 UTC, hyu7000 commented
thank you for letting me know code to change.
changed some code. check it please.

2021-10-05 14:25 UTC, konskarm commented
Everything seems to be working without issues now so I am merging these. the Joyplace Cremaker printers should appear in Cura 4.12 onwards.

2021-10-05 14:26 UTC, merged