Fix duplicating / multiplicating support blockers
Ultimaker/Cura pull request #10562
Opened 2021-10-04 13:52 UTC by nallath

CURA-7851

2021-10-04 13:54 UTC, nallath commented
This should provide a fix for  https://github.com/Ultimaker/Cura/issues/8776

2021-10-06 12:41 UTC, konskarm requested changes
Some code-style changes and a request to simplify a small part. 
Also, bit of a nitpick, but I think that the new eraser node that is added should be moved at least a tiny bit. Right now it's not visible that it is multiplied if you don't have the Object list in the bottom left corner expanded, because it the new Eraser block is right under the old one.

2021-10-06 12:41 UTC, konskarm commented on cura/Arranging/Nest2DArrange.py
> +                                   add_new_nodes_in_scene: bool = False):
```suggestion
                                   add_new_nodes_in_scene: bool = False)  -> Tuple[GroupedOperation, int]:
```

2021-10-06 12:41 UTC, konskarm commented on cura/Arranging/Nest2DArrange.py
> +                                   set_position=True))
```suggestion
                TranslateOperation(node, Vector(200, node.getWorldPosition().y, -not_fit_count * 20), set_position = True))
```

2021-10-06 12:41 UTC, konskarm commented on cura/MultiplyObjectsJob.py
> +            group_operation = GroupedOperation()
This whole if statement can be simplified as follows:

``` python
group_operation = GroupedOperation()
if nodes:
    group_operation, not_fit_count = createGroupOperationForArrange(nodes,
                                                                            Application.getInstance().getBuildVolume(),
                                                                            fixed_nodes,
                                                                            factor = 10000, add_new_nodes_in_scene = True)
```

2021-10-06 12:41 UTC, konskarm commented on cura/MultiplyObjectsJob.py
>          found_solution_for_all = True
This variable seems to always be True now. Shouldn't it change based on the outcome of the `createGroupedOperationForArrange()`? 
If it doesn't, then the message `no_full_solution_message` later on can be removed.

2021-10-06 14:49 UTC, merged