add zmorph i500 printer
Ultimaker/Cura pull request #11008
Opened 2021-12-04 20:05 UTC by michallesniak2

I work for the Zmorph company. 
I added the definition files for our machine zmorph i500 to Cura.

2021-12-04 20:10 UTC, michallesniak2 commented
I also have the files for the material definitions, but I don't know how to add them. 
Can you tell me how should I implement them.

2022-02-14 15:20 UTC, Ghostkeeper requested changes

2022-02-14 15:20 UTC, Ghostkeeper commented on resources/definitions/zmorph_i500.def.json
> +        "machine_width": { "default_value": 440 },
On the product page of this printer, it says 460: https://zmorph3d.com/products/zmorph-i500/

Was this difference intentional?

2022-02-14 15:20 UTC, Ghostkeeper commented on resources/definitions/zmorph_i500.def.json
> +        "retraction_combing": { "default_value": "all" },
This setting override is not working. It is overridden by the `value` defined in fdmprinter, which is a formula. This is a way to make it override properly:

```suggestion
        "retraction_combing": { "value": "'all'" },
```

Or you could consider adjusting the formula from fdmprinter to make it dependant on whether ironing or monotonic is used.

2022-09-08 12:08 UTC, closed without merging