Printer profile "Vector"
Ultimaker/Cura pull request #11488
Opened 2022-02-15 19:52 UTC by Fireman68

Please add a profile of printers Vector 200 and Vector A4, from a Russian manufacturer.

2022-07-19 12:33 UTC, nallath requested changes
Apologies for the long time it took us to review this!

Also note that meshes of machines should be well below 1 mb. Try to keep them as compact as possible.

2022-07-19 12:33 UTC, nallath commented on resources/definitions/vector_200.def.json
> +            "0": "Vector_200_extruder_0"
```suggestion
            "0": "vector_200_extruder_0"
```

2022-07-19 12:33 UTC, nallath commented on resources/extruders/vector_a4_extruder_0.def.json
> +		"machine": "vector_A4",
```suggestion
		"machine": "vector_a4",
```

2022-07-19 12:33 UTC, nallath commented on resources/extruders/vector_200_extruder_0.def.json
> +    "id": "vector_200_extruder_0",
```suggestion
```

2022-07-19 12:33 UTC, nallath commented on resources/definitions/vector_a4.def.json
> +        "platform": "vector_A4.stl",
```suggestion
        "platform": "vector_a4.stl",        
```

2022-09-05 12:02 UTC, nallath commented
Could you have a look at the requested changes? Thanks!

2022-11-29 19:18 UTC, jellespijker commented
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

2026-09-14 17:46 UTC, GregValiant commented
No interest in this in a couple of years.  I'll go ahead and close this.

2026-09-14 17:46 UTC, closed without merging