Styling of preferences screens
Ultimaker/Cura pull request #11506
Opened 2022-02-18 15:30 UTC by nallath

The materials page isn't styled yet but noticed that i misunderstood the scope of the ticket and went a bit overbroad. 

CURA-8949 
https://github.com/Ultimaker/Uranium/pull/782

2022-02-19 11:53 UTC, casperlamboo requested changes
Code looks good. these new preference pages look so much better then before, great job @lorenzoromagnoli !

While component testing i did find some blemishes

There is something weird going on with the dropdownbox in the settings visibility page there is no left blue border when hovering
I think that "check all" checkbox should be a `UM.Checkbox` don't think that it is right now.
![Screenshot from 2022-02-19 11-30-57](https://user-images.githubusercontent.com/6638028/154797159-a2f83c17-0e05-4f19-8f11-3b63972a997d.png)

The italic text "you will need to restart" should be located under the checkbox.
![Screenshot from 2022-02-19 11-32-50](https://user-images.githubusercontent.com/6638028/154797220-99c500bd-f9c3-4e3d-b640-038a72260294.png)

2022-02-20 14:20 UTC, fieldOfView commented
What I think is odd about this redesign is that it seems to mix the Cura theme and the system theme. I would think that this move to QtQuick 2 is a good opportunity to move to a full Cura theme solution. That would reduce the maintenance of GUI elements (eg the ever-lurking issue of commas and periods in number fields, tabbing through fields, etc) and it would solve the issue of MachineAction dialogs having to work in both the Cura-themed first-run wizard and the system-themed preferences dialogs.

2022-02-21 07:04 UTC, casperlamboo commented
@fieldOfView we are slowly migrating to having everything upgraded to qtcontrols2/qt6. But due to the huge amount of components this takes a while. But. We're getting there

2022-02-21 08:43 UTC, nallath commented on resources/qml/Preferences/GeneralPage.qml
> +                Cura.SecondaryButton
Yeah, but the design also shows it as being an external link, but its not. I believe that it's a mistake in the design (It was misinterpreted as an external page but it's actually a popup)

2022-02-21 08:44 UTC, nallath commented
We are going to move over _all_ system styled stuff and completely move over to custom (and hopefully, consistently) styled items.

2022-02-21 08:52 UTC, nallath commented on resources/qml/Preferences/MachinesPage.qml
> +                Cura.MachineManager.renameMachine(base.currentItem.id, newName.trim())
Well, neither need it and in this case it was me trying to at least make it consistent with the next line.

2022-02-21 08:54 UTC, lorenzoromagnoli commented on resources/qml/Preferences/GeneralPage.qml
> +                Cura.SecondaryButton
ah, this is probably my bad. can we the learn more with this? 

![Screen Shot 2022-02-21 at 09 52 41](https://user-images.githubusercontent.com/2944758/154920798-bcb7f2c3-64c7-470a-ab45-e085f1132574.png)

notice the normal and hover state

2022-02-21 09:05 UTC, nallath commented on resources/qml/Preferences/GeneralPage.qml
> +            id: addMenuButton
Whoops, i must have copypasted it and forgot to remove that.

2022-02-21 09:06 UTC, nallath commented on resources/qml/Preferences/GeneralPage.qml
> +//        /setDefaultCameraMode(defaultCameraMode)
I'm not entirely sure. They seem to be referencing things that aren't there anymore, but I don't know what happened to them.

2022-02-22 09:10 UTC, merged