[CURA-8688] QT6 cleanup
Ultimaker/Cura pull request #11535
Opened 2022-02-23 14:50 UTC by Joeydelarago

Fix the styling of anything that changed the look of components in the Qt6 update.

2022-02-24 15:07 UTC, Ghostkeeper requested changes
A couple of minor changes from the code review. But I'm finding a bunch of bugs too, which are probably a lot more work.

- [ ] The Remote Support preferences dialogue has not yet been updated.
![image](https://user-images.githubusercontent.com/2448634/155539741-69b7c271-7ebc-4fc3-b971-fe3ec5c964d5.png)

- [ ] The post-processing scripts dialogue is a mix of system-styled and Cura-styled components.
![image](https://user-images.githubusercontent.com/2448634/155540895-980af364-68bf-4f72-b6b9-83bccf6a7b45.png)

- [ ] The preferences dialogue is a mix of system-styled and Cura-styled components.
![image](https://user-images.githubusercontent.com/2448634/155541130-e6ebe5d1-1c91-4142-9197-9420a4b9077a.png)

- [ ] It's hard to read the selected page in the preferences drop-down (see above screenshot) due to being white on light-blue.

- [ ] Disabled checkboxes are white in the dark theme.
![image](https://user-images.githubusercontent.com/2448634/155541344-63e1e4b4-8ddb-4f64-a45d-38ee67f866a1.png)

- [ ] It's hard to read the headers and see the icons in the setting visibility dialogue due to being black on dark-grey in the dark theme.
![image](https://user-images.githubusercontent.com/2448634/155541584-bbf9bd69-acbf-473d-849c-395215c7ef6c.png)

- [ ] The left border line is missing from the visible-setting-profile selection in the setting visibility dialogue. The elements in this drop-down are also taller than other ones. I can't take screenshots of drop-downs though (the screenshot tool closes the drop-downs).

- [ ] The setting visibility search bar is not styled.
![image](https://user-images.githubusercontent.com/2448634/155541951-3bb8f7c2-9f0f-451a-a1fe-e3a82a73b462.png)

- [ ] The network connecting screen is a mix of system-style and Cura style.
![image](https://user-images.githubusercontent.com/2448634/155542106-74249ec4-4969-406b-86a1-5b7747723cae.png)

- [ ] Message dialogues don't follow the dark theme, although text and text fields inside do.
![image](https://user-images.githubusercontent.com/2448634/155542696-585d8469-bbc5-4f96-b09a-ad87d5a90871.png)

- [ ] The machine settings dialogue is a mix of system style and Cura style.
![image](https://user-images.githubusercontent.com/2448634/155542895-f70e74a8-9f9e-4dac-ac9f-bbf2f6d316f5.png)

- [ ] Only the selected item and the text follows the theme in context menus, leaving the rest unreadable.
![image](https://user-images.githubusercontent.com/2448634/155543860-9a698bec-6902-447b-97d5-1548cce13b62.png)

- [ ] The rename profile dialogue is not yet updated.
![image](https://user-images.githubusercontent.com/2448634/155544030-82e338bf-4440-40c9-814f-64834052801a.png)

- [ ] The monitor page for network-connected printers doesn't load. The following error gets put in the log:
```
QQmlComponent: Component is not ready
2022-02-24 15:33:47,120 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [603]: file:///home/trin/Gedeeld/Projects/Cura/plugins/UM3NetworkPrinting/resources/qml/MonitorStage.qml:47:13: Type MonitorCarousel unavailable
2022-02-24 15:33:47,121 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [603]: file:///home/trin/Gedeeld/Projects/Cura/plugins/UM3NetworkPrinting/resources/qml/MonitorCarousel.qml:138:17: Type MonitorPrinterCard unavailable
2022-02-24 15:33:47,121 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [603]: file:///home/trin/Gedeeld/Projects/Cura/plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml:228:9: Type MonitorContextMenu unavailable
2022-02-24 15:33:47,121 - ERROR - [MainThread] UM.Qt.QtApplication.createQmlComponent [603]: file:///home/trin/Gedeeld/Projects/Cura/plugins/UM3NetworkPrinting/resources/qml/MonitorContextMenu.qml:136:5: Cura.MessageDialog - Cura is neither a type nor a namespace
```
I think it's missing an import.

- [ ] Radio buttons don't go with the dark theme. Is this intended?
![image](https://user-images.githubusercontent.com/2448634/155544694-16bf5e33-7ba4-4c68-aed4-b08a9d8eb46b.png)

- [ ] The print profile assistant doesn't load any more. When opening that stage, the following error gets put in the log:
```
2022-02-24 15:36:06,073 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [428]: file:///home/trin/Gedeeld/Projects/Cura/plugins/CuraPrintProfileCreator/PrintProfileCreator/../components/CuraPrintProfileCreatorView.qml:43:9: Type ProfileCreatorManager unavailable
2022-02-24 15:36:06,073 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [428]: file:///home/trin/Gedeeld/Projects/Cura/plugins/CuraPrintProfileCreator/PrintProfileCreator/../components/ProfileCreatorManager.qml:109:13: Cannot assign to non-existent property "onYes"
```
I think this entire plug-in was forgotten. I find it helpful to keep the plug-ins we maintain loaded at all time so that we don't forget them ;)

- [ ] The Marketplace doesn't open any more at all. Nothing gets added to the log when pressing that button. Nothing happens also when going to the Marketplace via Settings -> Extruder 1 -> Material -> Add more materials from Marketplace.

- [ ] The open project summary is partially system-styled and partially Cura-styled.
![image](https://user-images.githubusercontent.com/2448634/155545559-679d4b82-b523-4b05-929c-758e0aa9cf7e.png)

- [ ] The printer cards in the material sync wizard suddenly got like 4x as big.
![image](https://user-images.githubusercontent.com/2448634/155546324-96312fb6-4801-4f9a-9540-11f65ea52d45.png)

- [ ] The open project file dialogue is partially system-styled and partially Cura-styled.
![image](https://user-images.githubusercontent.com/2448634/155546836-e18a474e-e6b7-48ef-909a-a97bfe9e30ea.png)

- [ ] The keep-or-discard-changes dialogue is partially system-styled and partially Cura-styled.
![image](https://user-images.githubusercontent.com/2448634/155546962-10c1ae04-56a2-443f-ab68-8a2d2a5f8644.png)

- [ ] The save project dialogue is partially system-styled and partially Cura-styled. The checkbox there is not styled at all.
![image](https://user-images.githubusercontent.com/2448634/155547875-e28d8e8f-bdb1-4b9d-9bea-4342bafbe186.png)

- [ ] Text in the tool panels is system-styled.
![image](https://user-images.githubusercontent.com/2448634/155548254-1e472920-edb7-46a5-ac94-c82206de57cb.png)

- [ ] The Multiply Models dialogue is partially system-styled and partially Cura-styled. Also, the spinbox in there seems to have such a small width that the buttons overlap and the text is misaligned.
![image](https://user-images.githubusercontent.com/2448634/155549101-b8b52c33-2b5c-46fb-8eba-1e582c52d321.png)

- [ ] The selection for per-object settings is partially system-styled and partially Cura-styled.
![image](https://user-images.githubusercontent.com/2448634/155549420-aa7ce356-f973-42e5-bb13-70cd0369505e.png)

- [ ] The about dialogue is partially Cura-styled and partially system-styled.
![image](https://user-images.githubusercontent.com/2448634/155550390-2afc4abd-0661-4b42-ab62-9dc20b311aa5.png)

2022-03-01 15:05 UTC, rburema reviewed
Very small remarks.

2022-03-02 10:00 UTC, rburema commented on resources/themes/cura-light/theme.json
> +        "expandable_active": [240, 240, 240, 255],
Don't worry about it, I mostly wanted just to make you aware of it, if you weren't already.

2022-03-02 15:49 UTC, rburema approved these changes

2022-03-02 15:49 UTC, merged