[CUBICON] Add models (Optimus-C23, Prime-M22)
Ultimaker/Cura pull request #11563
Opened 2022-02-27 07:13 UTC by HUNIBEST-HyVISION

Add models (Optimus-C23, Prime-M22)

2022-04-19 08:28 UTC, nallath requested changes

2022-04-19 08:28 UTC, nallath commented on resources/extruders/cubicon_style_neo_a22_extruder_0.def.json
> +        "machine": "ultimaker2_plus",
This isn't correct. This extruder isn't for the Ultimaker2_plus

2022-04-19 08:28 UTC, nallath commented on resources/definitions/cubicon_style_neo_a22.def.json
> -    "version": 2,
Why are you removing this printer? This will cause configurations to become corrupted.

2022-04-25 01:39 UTC, closed without merging

2022-04-25 01:41 UTC, HUNIBEST-HyVISION commented
This is the test code tested because a build error occurred after the profile merge.