Add Blocks machines to ultimaker cura
Ultimaker/Cura pull request #11620
Opened 2022-03-07 11:34 UTC by jgrilo-blocks

First definitions of Blocks machines for Ultimaker Cura

2022-03-16 16:03 UTC, Ghostkeeper commented
Belongs to https://github.com/Ultimaker/fdm_materials/pull/195. They should be merged at the same time.

The tests are currently failing. It fails for a lot of files, but it seems that at least for some of them it's because the SettingVersion is outdated (should be 19 instead of 17). That indicates that you might have tested this in Cura 4.13 instead of in Cura 5.0. Do they work with Arachne?

2022-03-16 16:45 UTC, jgrilo-blocks commented
Thanks for the feedback @Ghostkeeper, yeah i tested them on Cura 4.13 but they work in Arachne, i will fix the SettingVersion of the files

2022-03-23 09:44 UTC, Ghostkeeper commented
You can just update the master branch of BlocksTechnology's fork with new commits. Github will automatically update this Pull Request with your latest changes. That's also the easiest for us.

2022-06-22 13:13 UTC, braga-dev commented
@Ghostkeeper any updates when this branch will be merged?

2022-09-15 12:22 UTC, nallath submitted a review, later dismissed
Apologies for the slow review! I'm trying to get through all the open PR's again.

I've not checked all the settings, but I've found quite a few settings that re-define defaults. This makes it a lot harder to maintain the profile, so it's generally best to adhere to the DRY (Don't repeat yourself) as much as possible.

Furthermore, we also require buildplate meshes to be well below 1mb. Try to exclude any unneeded details like springs / screws.

2022-09-15 12:22 UTC, nallath commented on resources/quality/blocks/Nozzle/blocks_global_0.20_standard.inst.cfg
> +material_diameter = 1.75
This should not be set in a quality profile. It's already being set by the extruder. THese can (and should) be removed from all of them.

2022-09-15 12:22 UTC, nallath commented on resources/quality/blocks/Nozzle/blocks_global_0.20_standard.inst.cfg
> +setting_version = 19
setting version is 20 now (not a big deal if you don't fix it, but it will make the tests fail right now)

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_pros30.def.json
> +
```suggestion
```
Remove unneeded whitespaces

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "retraction_enable": { "value": true },
```suggestion
```
This is already the default in fdmprinter, no need to repeat yourself.

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +      "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
```suggestion

```
Already the default, no need to repeat yourself

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +      "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
```suggestion

```

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +      "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
```suggestion

```

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "material_flow": { "value": 100 },
```suggestion

```
The default material print temperature is 100 by default.

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    },
```suggestion

```
The default value uses a more robust variant that is effectively the same.

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "jerk_enabled": { "value": false },
```suggestion

```
Default values, no need to repeat yourself.

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "speed_infill": { "value": "speed_print" },
```suggestion
```
Default value

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "speed_wall_0": { "value": "speed_wall" },
```suggestion

```

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "speed_roofing": { "value": "speed_topbottom" },
```suggestion

```

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_base.def.json
> +    "wall_line_width": { "value": "machine_nozzle_size" },
```suggestion

```

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_pros30.def.json
> +    "retraction_retract_speed": { "value": 40, "maximum_value_warning": 130 },
Why not just define the maximum value_warning in the base file? THey seem to be the same for all machines.

2022-09-15 12:22 UTC, nallath commented on resources/definitions/blocks_pros30.def.json
> +    "speed_print": { "value": 50 },
It's the same for all printers. So why not just put it in the base file?

2022-10-14 16:44 UTC, braga-dev commented
@nallath changes were made and machines added. Thank you so much for the help

2022-11-05 15:30 UTC, braga-dev commented
@nallath any chance to review the printer and quality profiles? thank you

2022-11-29 19:18 UTC, jellespijker commented
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

2022-12-16 12:03 UTC, braga-dev commented
hello @jellespijker just sync the fork and waiting for the confirmation. thank you

2022-12-19 21:52 UTC, braga-dev commented
@jellespijker how are you? is it possible to approve the workflow to check if there is more diagnostics with printer-liner? thank you

2022-12-30 11:21 UTC, braga-dev commented
@jellespijker just updated with the last commits! Let's hope its the final one :D

2022-12-30 23:24 UTC, jellespijker requested changes
Still multiple issues and failing Unit Tests so I can't press merge :-( 

To help you guys out a bit I made a PR against your fork. See https://github.com/BlocksTechnology/Cura/pull/1

If you agree with these suggested changes feel free to merge it on your fork, this should also update this PR.

I will convert this PR to a WIP PR. You can convert it back once it is ready to be reviewed again.

2023-01-06 09:28 UTC, jellespijker commented
@braga-dev and @jgrilo-blocks Do you guys need additional help with this PR? Or is merging my PR on your fork enough? https://github.com/BlocksTechnology/Cura/pull/1

It would be nice if we can add your printers in Cura 5.3.0

2023-01-06 18:30 UTC, braga-dev commented
hello @jellespijker sorry for the delay. We just fixed the last issue so its all probably fine. We already tested these print profiles in Cura 5 and they are working fine so there won't be a problem. 

For future updates, its going to be easier/faster than the first ones right?

2023-01-06 18:41 UTC, jellespijker commented
Don't worry. The main delay was originally on our side. We are finally catching up.

Yes, updates and new printers should now be processed way faster due to our improved workflow.

I will take a look at the fixes first thing o Monday. Good to hear that they have been tested on Cura 5.x.

If all goes well, these printers should be available in Cura 5.3

2023-01-06 18:43 UTC, jellespijker commented
just mark it ready for review when you're finished so we know that we can review it.

2023-01-06 18:51 UTC, braga-dev commented
Hello @jellespijker perfect. Great to hear that.

2023-01-10 07:32 UTC, jellespijker approved these changes
LGTM;

Two minor fixes which I will quickly fix myself when I merge it.
Congrats guys, your printers should be available in Cura 5.3

2023-01-10 07:32 UTC, jellespijker commented on resources/definitions/blocks_base.def.json
> +            "deafult_value": 20,
```suggestion
            "default_value": 20,
```

2023-01-10 07:32 UTC, jellespijker commented on resources/definitions/blocks_base.def.json
> +            "deafult_value": 40,
```suggestion
            "default_value": 40,
```

2023-01-10 07:32 UTC, jellespijker commented on resources/definitions/blocks_base.def.json
> +            "deafult_value": 20,
I will change these myself after I merge them

2023-01-10 07:32 UTC, jellespijker commented on resources/definitions/blocks_base.def.json
> +            "deafult_value": 40,
I will change these myself after I merge them

2023-01-10 07:34 UTC, merged

2023-01-13 09:51 UTC, braga-dev commented
Hello @jellespijker ! Thank you very much! Can't wait.