Add printer profile for Modix3D printers
Ultimaker/Cura pull request #11682
Opened 2022-03-18 10:38 UTC by ComedianTF2

Has printer profiles for the Modix V3 line of printers: the Big40, 60, 120X, 120Z, 180X and Meter

2022-03-21 09:52 UTC, nallath requested changes

2022-03-21 09:52 UTC, nallath commented on resources/definitions/modix_base.def.json
> +            "ultimaker_abs_black",
No need to exclude these, they are 2.85 mm materials.

2022-03-21 09:52 UTC, nallath commented on resources/definitions/modix_base.def.json
> +            "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
```suggestion
            "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
```
No need to set this; The default is already the same (DRY: Don't Repeat Yourself)

2022-03-21 09:52 UTC, nallath commented on resources/definitions/modix_base.def.json
> +            "maximum_value_warning": "machine_max_feedrate_e if retraction_enable else float('inf')",
There are other cases where this is also the case. I've not marked all of them.

2022-03-22 08:38 UTC, ComedianTF2 commented
Please hold on, I made some mistakes in that commit and need to fix it still

2022-03-22 09:16 UTC, ComedianTF2 commented
Updated the modix_base.def.json to delete any duplicates from the fdmprinter.def.json

2022-03-23 08:46 UTC, nallath commented
The version number of the profiles isn't correct. THat is why the tests are failing. It should be 19

2022-03-23 09:21 UTC, ComedianTF2 commented
Fixed the version number from Version 2 to Version 19

2022-03-23 09:40 UTC, nallath commented
Nope, sorry. Not the definition one. That should be 2. The version number for the profiles (setting_version = 17) should be 19.

2022-03-23 09:48 UTC, ComedianTF2 commented
> Nope, sorry. Not the definition one. That should be 2. The version number for the profiles (setting_version = 17) should be 19.

Fixed the profiles version from 17 to 19, fixed the base definition from 19 to 2

2022-03-25 08:24 UTC, nallath commented
The CI is still failing on some things.

 [MainThread] UM.Settings.DefinitionContainer._preprocessParsedJson [299]: Unable to override setting travel_compensate_overlapping_walls_0_enabled
[MainThread] UM.Settings.DefinitionContainer._preprocessParsedJson [299]: Unable to override setting fill_perimeter_gaps

Unnecessary default_values for ['retraction_prime_speed', 'retraction_retract_speed'] in /__w/Cura/Cura/tests/Settings/../../resources/definitions/modix_base.def.json

2022-03-25 08:38 UTC, ComedianTF2 commented
@nallath I'm a little confused about the retraction_prime_speed and retraction_retract_speed, as the default values in fdmprinter.def.json are set to 25, rather than the preferred 40.

2022-03-25 09:08 UTC, nallath commented
> @nallath I'm a little confused about the retraction_prime_speed and retraction_retract_speed, as the default values in fdmprinter.def.json are set to 25, rather than the preferred 40.

Correct. But the _value_ property of these is also set. So if you only change the default_value it won't actually change anything. If the value is set, that is what is used (and not the default_value).

2022-04-04 12:11 UTC, ComedianTF2 commented
@nallath Do you know what's causing the issue with the failing check?

2022-04-26 11:54 UTC, closed without merging

2022-04-28 16:15 UTC, ComedianTF2 commented
@Ghostkeeper Thanks for the info. The 5.0 launch looks very exciting and I understand the crunch taking priority.I'll be re-submitting the profile again tomorrow, hopefully it will work properly.