Hello Cura! I want to add our 3D printer preset
Ultimaker/Cura pull request #11813
Opened 2022-04-18 03:18 UTC by borhaa

Thank you for make the Ultimaker Cura!
I create pull request to add our 3D printer "Stick printer - stick classic" !
(We are 3D printer company in South Korea)

We are using Cura but I didn't know how can I add our printer preset on Cura machine list.
(git hub is so hard to use to me..)
But I somehow learn github a bit, and Create pull request at long last.

If I did something wrong, (of course I hope not)
I will study again and try again...

Thank you again!

2022-09-08 12:27 UTC, nallath requested changes

2022-09-08 12:27 UTC, nallath commented on resources/definitions/stick_classic.def.json
> +        "quality_definition": "stick_base",
```suggestion
```
The definition doesn't exist, so you can't use it as a quality definition

2022-09-08 12:27 UTC, nallath commented on resources/definitions/stick_extruder_0.def.json
> +        "machine": "stocl_base",
stocl_base doesn't exist.

2022-11-29 19:18 UTC, jellespijker commented
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

2026-07-01 19:55 UTC, GregValiant commented
This has been sitting in limbo since 2022.  Can this be closed?

2026-09-14 17:44 UTC, GregValiant commented
I'll close this.

2026-09-14 17:44 UTC, closed without merging