PP-166 DD core variant files
Ultimaker/Cura pull request #12465
Opened 2022-06-07 11:13 UTC by Andi-ultimaker

DD core variant files for S3 & S5 printers

Relates to: PP-166

Needs to be pulled together with the following pull request in the Cura repository: https://github.com/Ultimaker/fdm_materials/pull/205

2022-06-13 12:23 UTC, rijkvanmanen requested changes
I think this PR needs a bit more of discussion. Why not only put the machine_nozzle_id, machine_nozzle_size, machine_nozzle_tip_outer_diameter in this file? The rest can be put in the quality profiles and has nothing to do with the nozzle, right? The same reasoning is followed in Colorado.

2022-06-13 12:28 UTC, Andi-ultimaker commented
> I think this PR needs a bit more of discussion. Why not only put the machine_nozzle_id, machine_nozzle_size, machine_nozzle_tip_outer_diameter in this file? The rest can be put in the quality profiles and has nothing to do with the nozzle, right? The same reasoning is followed in Colorado.
> 
> Please note that a PR to remove these profiles from private_data is also lacking.

I copied the cfg files from the CC 0.4 core, so whatever was there has been copied in.

2022-06-15 11:59 UTC, Ghostkeeper commented
The profiles are designed to allow concentrating setting overrides if they are common in all subprofiles of a configuration. If the nozzle profiles were meant to only have the metadata of the nozzle ID and diameter in them, I don't think we'd make them into profiles. Effectively this is saying that all profiles with DD cores use an initial layer speed of 20mm/s, so then I don't see the need to make that specific to to a specific profile.

Putting them here makes it easier to change for you.

We'll merge this in now though, since we have a feature freeze now.

2022-06-15 11:59 UTC, Ghostkeeper approved these changes

2022-06-15 12:08 UTC, merged