add A30M/A30T/Mizar/Mizar_S profiles
Ultimaker/Cura pull request #12552
Opened 2022-06-18 06:53 UTC by alexwoo1900

Add profiles for 4 Geeetech machines

- A30M
- A30T
- Mizar
- Mizar S

2022-07-20 07:51 UTC, alexwoo1900 commented
Cura no longer supports third-party printers?

2022-07-20 10:00 UTC, nallath commented
We do, we've just been very busy. I've merged a bunch of definitions yesterday.

2022-09-19 13:52 UTC, nallath requested changes
There also seems to be a merge conflict. It seems that someone else has already contributed one of the machines that you're trying to add.

2022-09-19 13:52 UTC, nallath commented on resources/extruders/geeetech_A30M_extruder0.def.json
> +                      },
This file has very strange formatting. Could you please pass it through a JSON linter?

2022-09-19 13:52 UTC, nallath commented on resources/definitions/geeetech_A30M.def.json
> +        "machine_head_with_fans_polygon": { "default_value": [[-75,35],[18,35],[18,-18],[-75,-18]] },
```suggestion
        "machine_head_with_fans_polygon": { "default_value": [[-75, 35], [18, 35], [18, -18], [-75, -18]] },
```

2022-09-19 13:52 UTC, nallath commented on resources/definitions/geeetech_A30T.def.json
> +        "machine_extruder_trains":  { "0": "geeetech_A30T_extruder0","1": "geeetech_A30T_extruder1","2": "geeetech_A30T_extruder2" }
```suggestion
        "machine_extruder_trains":  { "0": "geeetech_A30T_extruder0", "1": "geeetech_A30T_extruder1", "2": "geeetech_A30T_extruder2" }
```

2022-09-19 13:52 UTC, nallath commented on resources/definitions/geeetech_A30T.def.json
> +        "machine_head_with_fans_polygon": { "default_value": [[-75,35],[18,35],[18,-18],[-75,-18]] },
```suggestion
        "machine_head_with_fans_polygon": { "default_value": [[-75, 35], [18, 35], [18, -18], [-75, -18]] },
```

2022-09-19 13:52 UTC, nallath commented on resources/definitions/geeetech_A30T.def.json
> +        "machine_center_is_zero": { "default_value": false},
```suggestion
```

DRY principle. This is already the default, no need to redefine it.

2022-11-29 06:45 UTC, closed without merging