[CURA-9401] Toolbar visible on monitor page
Ultimaker/Cura pull request #12600
Opened 2022-06-24 14:58 UTC by Joeydelarago

Fix a bug where the toolbar was showing on the monitor screen. The fix is to have a boolean in CuraStage objects which says whether they should show the toolbar. I think this will be useful for plugin developers.

The default is not to show the toolbar now. I expect this will not change the functionality of plugins, however if a reviewer thinks a default of true is more sensible please suggest the change.

2022-06-24 15:38 UTC, fieldOfView commented
I am not sure if I like the default to false.

2022-06-24 19:07 UTC, nallath commented
Why not just change the draw order? That's a much simpler way of doing this...

2022-06-29 08:47 UTC, nallath requested changes
A much simpler solution is to remove the `z: 1` property from the toolbar qml element.

2022-07-05 11:44 UTC, nallath commented
Closing this in favor of https://github.com/Ultimaker/Cura/commit/bafffa994c5b8e0bf0782a0d177456bc26b58560

2022-07-05 11:44 UTC, closed without merging