Add naxe machines, quality and materials
Ultimaker/Cura pull request #12697
Opened 2022-07-07 14:59 UTC by Naxecorp

Hello there, 

Here is some files for adding Naxe manufacturer in the Cura software.
We are based in France. 

Thank you all guys

2022-07-19 13:14 UTC, nallath requested changes
The STL is also too big. We require buildplate meshes to be well below 1mb.

2022-07-19 13:14 UTC, nallath commented on resources/materials/naxe_ABS.xml.fdm_material
> +<?xml version='1.0' encoding='utf-8'?>
Materials need to go in https://github.com/ultimaker/fdm_materials

2022-07-19 13:14 UTC, nallath commented on resources/materials/naxe_ABS.xml.fdm_material
> +      <brand>Naxe</brand>
Is this really a fundamentally different material? It seems like it's better to just add machine settings to generic 1.75 ABS instead

2022-07-19 14:02 UTC, Naxecorp commented
Thank you!
please have a look to my new commit ;)

2022-09-06 13:50 UTC, nallath commented
Apologies! I've noticed another mistake while i was testing this. Because you set the material_print_temperature in the quality files to have a certain value (eg; a hardcoded one), it's no longer using whatever is defined in the material. 

So as a rule of thumb, it's better to use 
material_print_temperature = =default_material_print_temperature + 10 
If you want to use the default value of the material but print it at a higher temp.

2022-09-06 14:17 UTC, Naxecorp commented
Hi nallath, 
Thanks for reply, I have made the changes. Feel free to comment this out.

2022-09-15 11:53 UTC, merged