ExtruderStack.py: clarify limit_to_extruder logic
Ultimaker/Cura pull request #13002
Opened 2022-08-11 10:59 UTC by digitalfrost

Simplify and clarify logic linked to limit_to_extruder
in getProperty method.
If statements are now less tangled and duplicated.

2022-09-06 13:09 UTC, nallath approved these changes

2022-09-06 13:12 UTC, nallath commented
This doesn't work. I get the following error: 

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jaime/Development/Cura/cura/CuraApplication.py", line 63, in <module>
    from cura.Machines.Models.FavoriteMaterialsModel import FavoriteMaterialsModel
  File "/home/jaime/Development/Cura/cura/Machines/Models/FavoriteMaterialsModel.py", line 4, in <module>
    from cura.Machines.Models.BaseMaterialsModel import BaseMaterialsModel
  File "/home/jaime/Development/Cura/cura/Machines/Models/BaseMaterialsModel.py", line 14, in <module>
    from cura.Settings.CuraContainerRegistry import CuraContainerRegistry
  File "/home/jaime/Development/Cura/cura/Settings/CuraContainerRegistry.py", line 26, in <module>
    from . import ExtruderStack
  File "/home/jaime/Development/Cura/cura/Settings/ExtruderStack.py", line 146
    limit_to_extruder = str(limit_to_extruder) if limit_to_extruder
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: expected 'else' after 'if' expression

2022-09-06 18:34 UTC, digitalfrost commented
Sorry, that was a Ruby style if one liner...

2022-09-06 18:42 UTC, digitalfrost commented
I think a normal if statement now reads better ...

2022-10-21 08:53 UTC, Joeydelarago requested changes
I'm getting a recursion error here.

2022-10-21 08:53 UTC, Joeydelarago commented on cura/Settings/ExtruderStack.py
> +        if limit_to_extruder != self.getMetaDataEntry("position"):
This case is entered when limit\_to\_extruder is None, which it did not before.

Also if the defaultExtruderPosition is -1 this case is also entered. I'm not sure how likely this is but it is best to code a bit defensively.

2024-02-16 09:49 UTC, saumyaj3 commented
Hey @digitalfrost! We believe this issue won't be picked up anytime soon, so I will be deferring the issue so we can focus on the most requested and needed features and bug fixes from our community and from Ultimaker
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs.  So, thanks again, and please let us know if you run into any other issues 💪

2024-02-16 09:49 UTC, closed without merging