[CURA-9483] Remove unused files
Ultimaker/Cura pull request #13185
Opened 2022-09-01 07:54 UTC by Joeydelarago

2022-09-01 08:17 UTC, nallath approved these changes

2022-09-05 06:01 UTC, jellespijker commented
@Joeydelarago are you sure you got everything?
I quick scan also raised some question with me if the following files are still being used by us:

- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/GitVersion.yml
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.appdata.xml
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.desktop.in
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/cura.sharedmimeinfo
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_coverage.py
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_mypy.py
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/pytest.ini

Please double check the files above on current usage and remove them if unused

2022-09-05 06:03 UTC, jellespijker requested changes
@Joeydelarago are you sure you got everything?
I quick scan also raised some question with me if the following files are still being used by us:

- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/GitVersion.yml
- [x] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.appdata.xml
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.desktop.in
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/cura.sharedmimeinfo
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_coverage.py
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_mypy.py
- [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/pytest.ini

Please double check the files above on current usage and remove them if unused

2022-09-06 09:27 UTC, Joeydelarago commented
> @Joeydelarago are you sure you got everything? I quick scan also raised some question with me if the following files are still being used by us:
> 
> *   [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/GitVersion.yml
> *   [x] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.appdata.xml
> *   [x] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/com.ultimaker.cura.desktop.in
> *   [x] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/cura.sharedmimeinfo
> *   [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_coverage.py
> *   [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/run_mypy.py
> *   [ ] https://github.com/Ultimaker/Cura/blob/CURA-9483_clean_up_CICD/pytest.ini
> 
> Please double check the files above on current usage and remove them if unused

The files I've checked here seem to be important for the linux AppImage. I can't really test this (Mac User) so I will leave them in for now.

2022-09-07 13:51 UTC, merged