official profile for Geeetech printers
Ultimaker/Cura pull request #13973
Opened 2022-12-05 10:58 UTC by whoseyoung

Re-modify and add some series of printer parameter configurations.

24 Geeetech printers, including 9 series models.
Thunder series. A high-speed printer and the maximum printing speed can reach 300 mm/s.
Mizar series. A machine that has very exquisite print quality and ultra quiet printing.
Other Geeetech printers.
---Request from Geeetech offical . All relevant tests have passed.

2022-12-07 02:29 UTC, whoseyoung commented
All issue items processed.

2022-12-10 09:24 UTC, whoseyoung commented
Changes requested by the bot have been made, and conversations resolved. Let me know if any additional items are needed or if there are any questions.

2022-12-10 15:42 UTC, jellespijker commented
Can't merge this yet, since it has failing UnitTests, See https://github.com/Ultimaker/Cura/actions/runs/3664838630/jobs/6195513166#step:13:549

2022-12-10 15:43 UTC, jellespijker requested changes
Check the failing UnitTests

2022-12-13 07:08 UTC, whoseyoung commented on resources/definitions/geeetech_Thunder.def.json
> +		"material_flow_layer_0": { "value": 95 },
fixed the redundant-override problem.

2022-12-13 19:40 UTC, jellespijker commented
LGTM;

Thank you for your contribution, will merge this to main, they should be available in Cura 5.3

2022-12-13 19:41 UTC, jellespijker approved these changes

2022-12-13 19:41 UTC, merged

2023-05-05 09:07 UTC, whoseyoung commented
After Cura5.3.1, it was found that this configuration was merged or replaced. Please help restore this configuration file, thank you