Fixed error in 0.8mm profiles for PC and CPE+
Ultimaker/Cura pull request #13987
Opened 2022-12-07 16:12 UTC by pkuiper-ultimaker

The 0.15mm mode was generated iso 0.2mm

Relates to: PP-277

2022-12-08 08:53 UTC, rijkvanmanen requested changes
I would suggest for this PR to keep the original names and include the name changes in PP-222. Next to this I see one setting change for PC and a lot of settings change for CPEp.

2022-12-08 09:02 UTC, pkuiper-ultimaker commented
> I would suggest for this PR to keep the original names and include the name changes in [PP-222](https://ultimaker.atlassian.net/browse/PP-222). Next to this I see one setting change for PC and a lot of settings change for CPEp.

The names of the files have not been changed. They are still the old profile names. 
For some reason CPE+ shows a deleted file (0.15mm) and than an new file (0.2mm), but PC shows a rename of the file.
I think the files are correct, so I do not know what to change.

2022-12-08 09:38 UTC, rijkvanmanen approved these changes

2022-12-13 15:20 UTC, jellespijker approved these changes

2022-12-13 15:20 UTC, merged