Added settings for max volumetric flow rate
Ultimaker/Cura pull request #14452
Opened 2023-02-01 20:08 UTC by mjc-506

# Description

Added settings for max volumetric flow rate

This fixes https://github.com/Ultimaker/Cura/issues/5248 (together with another PR for CuraEngine)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

A new "Max filament flow rate" setting has been added, defaulting to 0.0 (no effect). Setting this to (say) 10mm3/sec to suit a particular extruder reduces the print head velocity to remain within this limit (especially useful with dymanic layer heights, or changing line widths etc).

Slicing STLs with this PR (and the CuraEngine one) results in slightly different Gcodes with different velocities, respecting the limit set.

**Test Configuration**:
* Operating System: Linux
* Cura 5.30 git
* CuraEngine 5.30 git

# Checklist:
- [X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [X] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [X] I have commented my code, particularly in hard-to-understand areas
- [NA] I have uploaded any files required to test this change

2023-02-09 00:30 UTC, mashuptwice commented
Thanks for putting in the work! I'll figure out

2023-02-09 02:26 UTC, mashuptwice commented
After compiling and having a look at the code, this PR really just adds the setting for max VMS, bot none of the functionality.

![Screenshot_20230209_031458](https://user-images.githubusercontent.com/54219098/217699890-ff807888-dd10-4b42-b2a1-e1f20f5bc799.png)
![Screenshot_20230209_031436](https://user-images.githubusercontent.com/54219098/217699896-b95d71e4-be5a-4e7f-b735-5664914dea1c.png)

Running a diff on two coarsely sliced files shows that all the feedrates are exactly the same. 

@mjc-506 Did you even test your work before creating this PR?

2023-03-24 14:27 UTC, casperlamboo requested changes
Contribution looks good! have some minor remarks, if possible please review them yourself as well.

2023-03-24 14:27 UTC, casperlamboo commented on resources/definitions/fdmprinter.def.json
> +                    "unit": "mm³/s",
You should use the unicode for the cubic $^3$ notation
```suggestion
                    "unit": "mm\u00b3/s",
```

2023-03-24 14:27 UTC, casperlamboo commented on resources/definitions/fdmprinter.def.json
> +                    "description": "When non-zero, sets the maximum allowed filament flow rate (in mm^3/S). The filament flow rate of each printed line is calculated as layer height * line width * pr
Made the description less verbose, and more consistent with the other setting descriptions
```suggestion
                    "description": "When greater then zero, the maximum allowed flow rate is limited to Max Filament Flow Rate (in mm\u00b3/s). The flow rate limit is enforced by reducing the print speed.",
```

2023-06-09 08:45 UTC, casperlamboo commented
See reply at https://github.com/Ultimaker/CuraEngine/pull/1814#issuecomment-1584200537

>  Hi @mjc-506 sorry for taking this long to get back to you. We have had quite some internal discussions about this feature, and unfortunately we have decided to take a different approach.
>
> We are afraid that, when using this new feature, the print behavior will become unpredictable. Instead we want to introduce a new feature that gives the user more insight whether flow jumps are violated, and can consequently change settings to make sure flow stays within an acceptable range.
>
> Hope you understand our decision.

2023-06-09 08:45 UTC, closed without merging