BUG fix & Improve some parameters & add 2 more productions
Ultimaker/Cura pull request #14522
Opened 2023-02-09 10:21 UTC by 3d-hctech

Meshes BUG fix & Improve some parameters & add 2 more productions
- Meshes bug fix for HC300-M1&M1H, HC300-M2H, HC300-M3. The original shows the wrong place in Cura.
- Improve the parameters of retraction, start & end scrips for HC300-M1&M1H, HC300-M2H, HC300-M3.
- Add HC300-M5 & HC500-M3 products of definitions, extruders, and meshes.

2023-06-09 09:29 UTC, nallath requested changes

2023-06-09 09:29 UTC, nallath commented on resources/definitions/hctech_hc300-m5.def.json
> +    "version": 1,
```suggestion
    "version": 2,
```
This is the version of the file format, not the version how often it was updated

2023-06-09 09:29 UTC, nallath commented on resources/definitions/hctech_hc300-m3.def.json
> +    "version": 3,
```suggestion
    "version": 2,
```
This is the version of the file format, not the version how often it was updated

2023-06-09 09:29 UTC, nallath commented on resources/definitions/hctech_hc300-m2h.def.json
> +    "version": 3,
```suggestion
    "version": 2,
```
This is the version of the file format, not the version how often it was updated

2023-06-09 09:29 UTC, nallath commented on resources/definitions/hctech_hc300-m1&m1h.def.json
> +    "version": 3,
```suggestion
    "version": 2,
```
This is the version of the file format, not the version how often it was updated

2026-09-14 18:03 UTC, GregValiant commented
It has been a couple of years.  I'll close this.  Let me know if that is premature.

2026-09-14 18:03 UTC, closed without merging