Updated elegoo definitions
Ultimaker/Cura pull request #14946
Opened 2023-03-18 16:02 UTC by Joeydelarago

# Description

Heyo, I finally got my printer 😎

This PR brings the Elegoo profiles in line with the Ultimaker profiles.

- Change quality names to match Ultimaker profiles
- Change quality layer heights to have bigger difference between qualities
- Add 0.2, 0.6 and 0.8 nozzle variants for pla

I mostly kept the settings that were already there for asa, pla, abs, petg 0.4 profiles

## Type of change

- [x] Printer definition file(s)

# How Has This Been Tested?

- [ ] Printing and loading up each material in each affected printer

**Test Configuration**:
* Operating System: Ubuntu 20.04 (LTS)

# Checklist:
- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

2023-03-21 13:42 UTC, jellespijker commented
Heyo,

Let's see if you learned something from your time with us ;-) 

Looking forward to reviewing this

2023-03-21 14:38 UTC, jellespijker requested changes
Looks almost like you know what you're doing ;-P But seriously, good to see you making a community contribution :heart:

A couple of small remarks regarding fortifying retrieval of setting. Try to use: `resolveOrValue()` where possible.

Also be aware that removing files requires an upgrade script.... my logs are spammed with error messages below. This happens if I have a Elegoo printer in 5.3.0 and upgrade to 5.4.0.

I will start writing an upgrade script for another ticket somewhere this week. I would love it if add the logic for upgrading the Elegoo printers in that script :heart: If you don't have time for that, I will try to add them myself somewhere in the coming weeks, just let me known.

```
2023-03-21 15:18:10,467 - ERROR - [MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
2023-03-21 15:18:10,468 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Exception: Error in the format of container ELEGOO NEPTUNE: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
2023-03-21 15:18:10,468 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Traceback (most recent call last):
2023-03-21 15:18:10,468 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/site-packages/UM/Settings/ContainerRegistry.py", line 215, in findContainers
2023-03-21 15:18:10,468 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     new_container = provider.loadContainer(metadata["id"])
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/plugins/LocalContainerProvider/LocalContainerProvider.py", line 84, in loadContainer
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     container.deserialize(f.read(), file_path)
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/cura_wp/Cura/cura/Settings/CuraContainerStack.py", line 309, in deserialize
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     serialized = super().deserialize(serialized, file_name)
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/site-packages/UM/Settings/ContainerStack.py", line 430, in deserialize
2023-03-21 15:18:10,469 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     raise ContainerFormatError("When trying to deserialize %s, we received an unknown container ID (%s)" % (self.getId(), container_id))
2023-03-21 15:18:10,470 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: UM.Settings.ContainerFormatError.ContainerFormatError: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
2023-03-21 15:18:10,471 - ERROR - [MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize ELEGOO NEPTUNE 3, we received an unknown container ID (elegoo_global_020_fine)
2023-03-21 15:18:10,471 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Exception: Error in the format of container ELEGOO NEPTUNE 3: When trying to deserialize ELEGOO NEPTUNE 3, we received an unknown container ID (elegoo_global_020_fine)
2023-03-21 15:18:10,472 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Traceback (most recent call last):
2023-03-21 15:18:10,472 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/site-packages/UM/Settings/ContainerRegistry.py", line 215, in findContainers
2023-03-21 15:18:10,472 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     new_container = provider.loadContainer(metadata["id"])
2023-03-21 15:18:10,472 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/plugins/LocalContainerProvider/LocalContainerProvider.py", line 84, in loadContainer
2023-03-21 15:18:10,473 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     container.deserialize(f.read(), file_path)
2023-03-21 15:18:10,473 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/cura_wp/Cura/cura/Settings/CuraContainerStack.py", line 309, in deserialize
2023-03-21 15:18:10,473 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     serialized = super().deserialize(serialized, file_name)
2023-03-21 15:18:10,473 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/site-packages/UM/Settings/ContainerStack.py", line 430, in deserialize
2023-03-21 15:18:10,474 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     raise ContainerFormatError("When trying to deserialize %s, we received an unknown container ID (%s)" % (self.getId(), container_id))
2023-03-21 15:18:10,474 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: UM.Settings.ContainerFormatError.ContainerFormatError: When trying to deserialize ELEGOO NEPTUNE 3, we received an unknown container ID (elegoo_global_020_fine)
2023-03-21 15:18:10,616 - ERROR - [MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
2023-03-21 15:18:10,617 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Exception: Error in the format of container ELEGOO NEPTUNE: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
2023-03-21 15:18:10,617 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]: Traceback (most recent call last):
2023-03-21 15:18:10,617 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/site-packages/UM/Settings/ContainerRegistry.py", line 215, in findContainers
2023-03-21 15:18:10,617 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     new_container = provider.loadContainer(metadata["id"])
2023-03-21 15:18:10,617 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/.conan/data/uranium/5.4.0-alpha+testing_22/ultimaker/testing/package/2522bab4dac4234dda1a8f85526096f67fc78645/plugins/LocalContainerProvider/LocalContainerProvider.py", line 84, in loadContainer
2023-03-21 15:18:10,618 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     container.deserialize(f.read(), file_path)
2023-03-21 15:18:10,618 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:   File "/home/jspijker/cura_wp/Cura/cura/Settings/CuraContainerStack.py", line 309, in deserialize
2023-03-21 15:18:10,618 - ERROR - [MainThread] UM.Settings.ContainerRegistry.findContainers [217]:     serialized = super().deserialize(serialized, file_name)
2023-03-21 15:18:10,618 - ERROR - [MainTh [...]

2023-03-21 14:38 UTC, jellespijker commented on resources/quality/elegoo/base/abs040/abs_040024.inst.cfg
Keep in mind that removing files requires an upgrade script, my logs are spammed with:
```
2023-03-21 15:18:10,467 - ERROR - [MainThread] UM.Settings.ContainerStack.deserialize [429]: When trying to deserialize ELEGOO NEPTUNE, we received an unknown container ID (elegoo_global_028_draft)
```

When I install some Neptune printers in 5.3.0 and then run your branch.

2023-03-21 14:38 UTC, jellespijker commented on resources/definitions/elegoo_base.def.json
>          "zig_zaggify_infill": { "value": "infill_pattern == 'cross' or infill_pattern == 'cross_3d' or infill_sparse_density < 30 " }
Best to use: `resolveOrValue()`

2023-03-28 14:14 UTC, jellespijker commented
@Joeydelarago can you do me a solid and make sure that your changes are added to the new upgrade script? That is basically the only thing blocking this ticket now

2023-04-06 11:16 UTC, Joeydelarago commented
> @Joeydelarago can you do me a solid and make sure that your changes are added to the new upgrade script? That is basically the only thing blocking this ticket now

Yessir, is this some kind of trick to get me to create an upgrade script 🤔🤔🤔🤔

Just kidding, I'll update my PR in the next few days. 

Hope all is going well at Cura!

2023-04-28 09:06 UTC, merged

2023-04-28 09:07 UTC, jellespijker commented
Thank you for your contribution @Joeydelarago , the profiles should be available in Cura 5.4

2023-09-02 22:01 UTC, phit commented
this broke all my profiles when trying to move to 5.4, can't import them manually either as the old quality type no longer exists