Elegoo 2 plus fix
Ultimaker/Cura pull request #15817
Opened 2023-06-19 22:33 UTC by GregValiant

# Description

There were typos in the Neptune 3Plus nozzle files.

## Type of change

- [ X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- [ X] Test A - The fix adds the nozzles to the 2Plus printer

**Test Configuration**:
* Operating System:  Windows 10

- [ X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [X ] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have uploaded any files required to test this change

2023-06-20 09:50 UTC, MariMakes commented
Hey @GregValiant,

Good to see you! Thanks for the PR!
It's the typo mentioned, [here](https://community.ultimaker.com/topic/43732-ultimaker-cura-54-beta-released/), right?

2023-06-20 13:06 UTC, GregValiant commented
That's it.  Right file but wrong definition.

2023-06-21 09:48 UTC, casperlamboo requested changes
Thanks @GregValiant , good catch!

If you can revert the changes on `ExampleScript` I will merge the PR.

2023-06-21 09:48 UTC, casperlamboo commented on plugins/PostProcessingPlugin/scripts/ExampleScript.md
> -https://github.com/Ultimaker/Cura/issues
Although this file is a bit non-sense, I don't think I should be removed in this PR.

2023-06-21 23:40 UTC, GregValiant commented
Hi Casper.
It's true...I suck at pull requests.  That wasn't intended to be part of it and I have no idea how it got in there.

2023-06-26 10:00 UTC, casperlamboo commented
Cherry picked the relevant changes directly to the 5.4 branch https://github.com/Ultimaker/Cura/commit/8b7339e399e69644a1364766e921ce877c567c42. Pushing that commit in favor of the PR; closing.

Thank you @GregValiant for the fix!

2023-06-26 10:00 UTC, closed without merging

2023-06-26 10:10 UTC, GregValiant commented
Perfect.