Display Info on LCD
Ultimaker/Cura pull request #15866
Opened 2023-06-22 17:26 UTC by GregValiant

# Description
DisplayInfoOnLCD combines DisplayFilenameAndLayerOnLCD with DisplayProgress.  Those two post processors become options within the single post processor and the two previous files become obsolete.  There is an option to add an M118 line as well as M117 so the info would get bounced back to a print server.
There is another pull request #11846 that involves "Display Progress on LCD" and BTREE firmware.
The Aug 12 commit adds "Countdown to Pauses" option when "Display Progress" is selected.
The Sep 8 commit adds an "Estimated Print Finish Time" message as an option per request #16677.  #6019 
Oct 20 commit adds a comment below the TIME: line and converts "seconds" to Housr:Minutes:Seconds with a pause and/or filament change count.
;TIME:14071
;Filament used: 13.3238m
;Layer height: 0.2
;Cura Time Estimate:  14071sec = 3hr 54min 31sec  with 1 pause(s) and 1 filament change(s)

## Type of change

- [ X] Updated feature

# How Has This Been Tested?

- [ X] Test A - Cura 4.x and 5.x

**Test Configuration**:
* Operating System:  Win10 Home and Marlin

# Checklist:

- [ X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [X ] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have uploaded any files required to test this change

2023-09-24 14:02 UTC, GregValiant commented
I was researching something else and came across a fact I had completely missed - RepRap can use M566 for Jerk in mm/min.
This PR adds support for M566.

2023-10-11 11:49 UTC, rburema requested changes
Hi Greg!

The big problem I have with this is that when you save a project, it saves which (post-processing) scripts where used as well. If it can't find them, it just ignores them -- which means that if the (now) removed scripts are added to a project, they'll no longer work, nor do they use the new script.

There's a number of ways to handle this.
- Writing an upgrade-script would be the most proper, but also the hardest (and I'm not sure if we can do that for upgrade scripts -- though it should be possible). Maybe a bit overkill?
- Leaving the scripts in, but messaging the user that the older scripts are deprecated.
- Only leaving shells of the scripts, and _only_ leave functionality in there to message the user.
- Rewriting the scripts so that they inherit from the new one.
- Not do anything (so reinstate them) and just have them live side-by-side until the next major version of Cura.
- ... or I can ask the rest of the team if it's ok that we just rip these out and just communicate the change well.

2023-10-11 11:49 UTC, rburema commented on plugins/PostProcessingPlugin/scripts/DisplayInfoOnLCD.py
> +                    if ";LAYER:" in line:
```suggestion
                    if line.startswith(";LAYER:"):
```

2023-10-11 11:49 UTC, rburema commented on plugins/PostProcessingPlugin/scripts/DisplayInfoOnLCD.py
> +                if ";TIME:" in line:
```suggestion
                if line.startswith(";TIME:"):
```

2023-10-11 23:39 UTC, GregValiant commented on plugins/PostProcessingPlugin/scripts/DisplayInfoOnLCD.py
> +                if ";TIME:" in line:
Done.

2023-10-11 23:40 UTC, GregValiant commented on plugins/PostProcessingPlugin/scripts/DisplayInfoOnLCD.py
> +                    if ";LAYER:" in line:
Done.

2023-10-11 23:41 UTC, GregValiant commented
The project file situation is something I hadn't thought of.  
The new script carries over "Display Filename and Layer on LCD" complete and I don't recall making changes to that script.
The second half of "Display Progress on LCD" is somewhat different with the time fudge factor, and Finish Time message, etc.  

As a user I think I would prefer a quick message to inform me to move to the new post processor.  If the script is left in then there is no incentive to move on and people will keep using it.

I've made changes to the two original scripts and turned them into "dummies" that just give messages.  What is your preference in handling this?

In addition, I made some additions and need to make another commit.  It will have the two changes you requested.

2023-11-24 12:59 UTC, rburema approved these changes
Hi Greg,
Sorry for the wait (again... it's been quite busy here).

I think we can accept this now. I _have_ noticed that this doesn't 100% replace the other two scripts (the possibility to set M73 instead of M117/8 is missing, and the update-frequency can only be once per layer), but I think this adds enough (and the consolidation itself is also a good thing), that it's still a good improvement. -- So let's just wait to see if anyone complains about those little thing.

Thanks again for the contribution, and I'll try to take another look at the other PRs again next week. (That big list was/is useful.)

2023-11-24 13:00 UTC, merged

2024-03-30 12:56 UTC, lethuer commented
I've observed some bugs in the new plugin: [DisplayInfoOnLCD.py](https://github.com/Ultimaker/Cura/blob/main/plugins/PostProcessingPlugin/scripts/DisplayInfoOnLCD.py)
and noted my obervations here: https://github.com/Ultimaker/Cura/issues/18766