Cura 8754 refresh button material sync list doesn't provide any feedback
Ultimaker/Cura pull request #16096
Opened 2023-07-10 12:37 UTC by saumyaj3

# Description

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System:

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

2023-07-10 12:48 UTC, saumyaj3 commented
Some checks are not successful because of failing workflow.

2023-07-11 08:37 UTC, nallath requested changes

2023-07-11 08:37 UTC, nallath commented on resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
> +                                        }
```suggestion
                                        refreshListButton.visible = accountState != _AccountSyncState_SYNCING   
```

The button just needs to be hidden if the syncing is happening, right? There are a few other states (like error), where the button should become visible again. 

That being said. I think you can even just use

`visible: Cura.API.account.syncState != _AccountSyncState_SYNCING    `

and get rid of the accountState property.

I'm not a 100% sure, but if i remember correctly, invisible buttons can still be clicked. If that's the case, you should also set the enabled property (enabled: visible)

2023-07-11 13:36 UTC, nallath approved these changes

2023-07-12 11:52 UTC, merged