[CURA-10829] Option to not use small skin areas on top
Ultimaker/Cura pull request #16429
Opened 2023-08-08 15:26 UTC by rburema

Please review & merge the other one first: https://github.com/Ultimaker/Cura/pull/16384

This one has a backend counterpart as well: (TODO make PR)

2023-08-09 11:51 UTC, pkuiper-ultimaker requested changes
**small_skin_width**
I'm planning to set this width to a very large value to cover the full skin area with walls. So this warning level will then be triggered, which is strange for our official profiles. My suggestion is to not set a warning level.
"maximum_value_warning": "skin_line_width * 3"

2023-08-10 08:01 UTC, rburema commented
@pkuiper-ultimaker Saumya had the same (re)quest(ion). She's going to remove the warning line, then hopefully we can merge it in as is now (though a bit of a regression was noted, which we'll investigate first).

2023-08-10 08:35 UTC, rburema commented
@pkuiper-ultimaker Also, question: If we want to fill the full skin area, then why not just set the skin-pattern to concentric?

2023-08-20 21:40 UTC, casperlamboo approved these changes

2023-08-22 08:15 UTC, merged