CURA-9374 Add scrollable area around text messages
Ultimaker/Cura pull request #16509
Opened 2023-08-18 14:31 UTC by wawanbreton

CURA-9374

Long messages are now scrollable. I reused the existing ScrollableTextArea, which has moved from Cura to Uranium, and changes the behavior of the user interactions :
* :+1: The text can now be selected, so the user may easily Google it in case of an error 
* :+1: The scrollbar only appears if the text is too high (fixed max size, to be discussed)
* :-1: When scrolling quickly, the last wheels moves actually zoom in/out on the 3d view

Maybe we should also consider making the dialog box a bit larger ?

2023-08-18 15:02 UTC, rburema requested changes
Looks good! However, I think we do need to keep the API the same. Like I suggested below, we could use a wrapper for that.

2023-08-21 07:20 UTC, wawanbreton commented on resources/qml/Widgets/ScrollableTextArea.qml
> -// Copyright (c) 2022 Ultimaker B.V.
OK, that is very wise indeed. Should they both be called `ScrollableTextArea` and have them distinguished with `Cura.ScrollableTextArea` and `UM.ScrollableTextArea` or should I find a different name for the new one in the Uranium part ?

2023-08-21 13:31 UTC, wawanbreton commented on resources/qml/Widgets/ScrollableTextArea.qml
> -// Copyright (c) 2022 Ultimaker B.V.
As discussed with @casperlamboo : keep the same name because this is really the same class.

2023-08-21 15:02 UTC, nallath approved these changes

2023-08-22 08:21 UTC, merged