CURA-11138-makerbot-cloud-printing
Ultimaker/Cura pull request #17149
Opened 2023-10-30 09:58 UTC by saumyaj3

CURA-11138

Makerbot printers in cloud

2023-10-31 10:07 UTC, rburema requested changes
Nice work!

I have a couple of small remarks.

I'm also not sure about the amount of hardcoding -- but I guess it can't be helped unless we want to spend a bunch more time on this (and also, we already do some similar things for UM printers...)

In the mean-time, I'll move this to component-test, so I can also check if all the subtasks have been done.

2023-10-31 10:55 UTC, saumyaj3 commented on cura/PrinterOutput/Models/ExtruderConfigurationModel.py
> +    def getHotendIdIfMakerbot(hotendId) -> str:
ce132e4c3f5292358a15c78ccd29aaace3e31f06

2023-10-31 11:32 UTC, saumyaj3 commented on plugins/DigitalLibrary/src/DFFileExportAndUploadManager.py
> +                    text = "'{}' was uploaded to '{}'.".format(filename_makerbot, self._library_project_name),
not needed as this was done for ufp files as well.

2023-10-31 11:33 UTC, saumyaj3 commented on plugins/DigitalLibrary/src/DFFileExportAndUploadManager.py
> +                    text = "Failed to upload the file '{}' to '{}'.".format(filename_makerbot, self._library_project_name),
ce132e4c3f5292358a15c78ccd29aaace3e31f06

2023-11-01 12:42 UTC, rburema approved these changes

2023-11-01 12:42 UTC, merged