[CURA-11300] Officially supported languages' translations for v5.6.x
Ultimaker/Cura pull request #17264
Opened 2023-11-08 15:07 UTC by rburema

Due to various circumstances, an excel spreadsheet, the .tsv export thereof, and a temporary, thrown together python script where involved this time. Please double-check thoroughly.

2023-11-10 15:28 UTC, casperlamboo requested changes

2023-11-10 15:28 UTC, casperlamboo commented on resources/i18n/nl_NL/fdmprinter.def.json.po
> +msgstr "Basis van de Prime Tower"
This isn't consistent with the previous translations, "Prime Tower" was always translated as "Primepijler". Although I do not like this translation I think we should keep consistent

```suggestion
msgstr "Basis van de Primepijler"
```

2023-11-10 15:28 UTC, casperlamboo commented on resources/i18n/nl_NL/fdmprinter.def.json.po
> +msgstr "Krachtmagnitude van de basiscurve van de Prime Tower"
```suggestion
msgstr "Krachtmagnitude van de basiscurve van de Primepijler"
```

2023-11-10 15:28 UTC, casperlamboo commented on resources/i18n/nl_NL/fdmprinter.def.json.po
> +msgstr "Hoogte van de basis van de Prime Tower"
```suggestion
msgstr "Hoogte van de basis van de Primepijler"
```

2023-11-10 15:28 UTC, casperlamboo commented on resources/i18n/nl_NL/fdmprinter.def.json.po
> +msgstr "Grootte van de basis van de Prime Tower"
```suggestion
msgstr "Grootte van de basis van de Primepijler"
```

2023-11-10 15:28 UTC, casperlamboo commented on resources/i18n/nl_NL/fdmprinter.def.json.po
> +msgstr "Lijnafstand van het vlot van de Prime Tower"
```suggestion
msgstr "Lijnafstand van het vlot van de Primepijler"
```

2023-11-15 13:57 UTC, casperlamboo approved these changes

2023-11-16 10:49 UTC, casperlamboo reviewed
I'm missing a few files,
- zh_TW/cura.po
- fi_FI/cura.po
- pt_BR/cura.po
- cs_CZ/cura.po

The first 2 are not important since they are not translated officially, but the last two might be of use for our translators

2023-11-17 09:33 UTC, merged

2023-11-18 13:31 UTC, rburema commented
None of those are officially translated -- at various points in time, they where all done by volunteer translators.

- For the 'Traditional Chinese' (not to be confused with 'Simplified Chinese', as used on the mainland), we had a volunteer, but I think they only properly responded to Ruben, I'm not sure if I ever received an answer when I wrote the request.
- The Finnish translation is the most out of date -- I'm not sure we ever did that particular one during the time we worked here.
- The Brazilian Portuguese one is done by a very enthusiastic volunteer (at the very least compared to the others...)
- I'm not sure what the status of the Czech one is. I think it might have been a recent addition (or recent resurgence), but I don't think we sent much in their direction for a few versions. (So this one might be on us/me...) -- Seeing them listed in this manner makes that more clear to me. I'll go see if I can clear that up next week.