Add raft settings to make margin and remove inside corners configurablle per raft-type
Ultimaker/Cura pull request #17945
Opened 2024-01-08 13:46 UTC by casperlamboo

# Description

Added the following settings
- raft_base_margin
- raft_interface_margin
- raft_surface_margin
- raft_base_smoothing
- raft_interface_smoothing
- raft_surface_smoothing
- raft_base_remove_inside_corners
- raft_interface_remove_inside_corners
- raft_surface_remove_inside_corners

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

**Test Configuration**:
* Operating System:
macOS 13.3

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

2024-01-08 16:49 UTC, wawanbreton requested changes

2024-01-09 09:22 UTC, casperlamboo commented on resources/definitions/fdmprinter.def.json
> +                            "limit_to_extruder": "adhesion_extruder_nr",
https://github.com/Ultimaker/Cura/pull/17945/commits/37f350b134d69518ef6455f214f152e4e04737b6

2024-01-09 09:22 UTC, casperlamboo commented on resources/definitions/fdmprinter.def.json
> +                    "children":
https://github.com/Ultimaker/Cura/pull/17945/commits/af51ccf5f37c5fdaf93bf31de307c5d3678f3691

2024-01-09 09:22 UTC, casperlamboo commented on resources/setting_visibility/expert.cfg
> +raft_surface_remove_inside_corners
https://github.com/Ultimaker/Cura/pull/17945/commits/4489b8db462e28777e24947fbcc09517566ecfe2

2024-01-09 09:23 UTC, casperlamboo commented on resources/definitions/fdmprinter.def.json
> +                            "maximum_value_warning": "20",
https://github.com/Ultimaker/Cura/pull/17945/commits/594e4a5ea67fc0266783dfe8052f2b3a8b0191cc

2024-01-09 15:48 UTC, merged