PP-423 Increase small skin width and wipe distance
Ultimaker/Cura pull request #18064
Opened 2024-01-18 14:54 UTC by pkuiper-ultimaker

Increase small skin width from 0.8mm to 4mm to prevent jerky moves in small skin areas. 
Increase wipe distance to 0.8mm to improve seam quality.
For Method machines.

PP-423

2024-01-31 12:45 UTC, wawanbreton approved these changes

2024-01-31 12:49 UTC, wawanbreton requested changes
This value is over the standard warning limit which is `2 * machine_nozzle_size`. Please consider changing the `maximum_value_warning` so that the new value fits

2024-02-05 10:20 UTC, pkuiper-ultimaker commented
> This value is over the standard warning limit which is `2 * machine_nozzle_size`. Please consider changing the `maximum_value_warning` so that the new value fits

I changed the warning value in the fdmprinter.def.json from 3 line widths to 10 line widths.

2024-02-05 12:06 UTC, wawanbreton approved these changes

2024-02-05 12:08 UTC, merged