Cura 12255 string fix translation
Ultimaker/Cura pull request #19846
Opened 2024-11-01 14:55 UTC by HellAholic

CURA-12255

![image](https://github.com/user-attachments/assets/bf99a301-b6b8-46e6-af9f-e1417f6eec11)

Comes with https://github.com/Ultimaker/conan-ultimaker-index/pull/15

2024-11-05 09:24 UTC, rburema requested changes

2024-11-05 09:24 UTC, rburema commented on resources/i18n/cs_CZ/fdmprinter.def.json.po
> +
Discussion results: We don't really want these in here, alter the 'variant-name' script to listen to a new 'should translate' (default = false) in fdmprinter.

2024-11-05 09:24 UTC, rburema commented on resources/i18n/cs_CZ/fdmprinter.def.json.po
> +
Same (see above).

2024-11-06 10:00 UTC, wawanbreton commented
We now have only 3 translated variants names:
* "Nozzle Size", used by default
* "Print Core", used by UM printers
* "Extruder", used by MB printers

2024-11-06 12:15 UTC, rburema approved these changes

2024-11-07 10:35 UTC, merged