adding profiles for Trimaker printers
Ultimaker/Cura pull request #8537
Opened 2020-10-14 13:26 UTC by tomasbaldi

Modification includes COSMOS II and NEBULA from Trimaker.

2020-10-14 13:37 UTC, tomasbaldi commented
why it generates an error?

2020-10-14 13:38 UTC, nallath commented
> why it generates an error?

Because we made a mistake with our CI system. It's entirely our fault.

2020-10-14 13:42 UTC, tomasbaldi commented
should i post it again? or wait? Thanks!

2020-10-14 13:58 UTC, nallath commented
Just wait :) No worries.

2020-10-15 11:43 UTC, konskarm commented
@tomasbaldi the tests ran properly now. Please have a look at the errors.

2020-10-27 15:54 UTC, tomasbaldi commented
@Ghostkeeper thank you very much! I am new in github!

2020-10-29 18:32 UTC, tomasbaldi commented
I don't understand why it keeps failing

2020-10-29 18:59 UTC, nallath commented on resources/extruders/trimaker_nebula_extruder.def.json
> +        "machine": "Trimaker Nebula",
```suggestion
        "machine": "trimaker_nebula",
```
It needs to reference to the ID of the machine, not the name.

2020-10-29 18:59 UTC, nallath commented on resources/extruders/trimaker_cosmosII_extruder.def.json
> +        "machine": "Trimaker Cosmos II",
```suggestion
        "machine": "trimaker_cosmosII",
```

2020-11-02 11:08 UTC, Ghostkeeper commented
A couple of issues are still left, as found by the automated tests:
* `trimaker_nebula_platform.stl` is 2MB. We limit the mesh files to 1MB to reduce download and storage size of Cura (there are ~300 printers in Cura, so this would grow pretty quickly otherwise).
* `trimaker_cosmosII.def.json` refers to a platform `trimaker_cosmosII_platform.stl` that doesn't exist.
* `trimaker_cosmosII.def.json` and `trimaker_nebula.def.json` override `default_value`s for `infill_pattern` and `xy_offset_layer_0` which are not applied, since those settings already have a `value` property. Try overriding `value` instead.

2020-11-12 12:39 UTC, konskarm commented
@tomasbaldi Could you have a look into @Ghostkeeper's comment?

2020-11-12 13:42 UTC, tomasbaldi commented
Sorry for the delay. Thank you very much for your contributions, they are very helpful to me. I just posted a new commit. I just need to raise the mesh again after lowering the quality.

2020-11-12 14:07 UTC, tomasbaldi commented
Thank you very much everyone for the help!

2020-11-17 01:20 UTC, tomasbaldi commented
Now we just have to wait?

2020-12-02 12:48 UTC, tomasbaldi commented
something happened with the request?

2020-12-03 10:50 UTC, konskarm commented
Hi @tomasbaldi. I was just looking into the PR. I notice three things:

* Both the buildplate platforms seem misaligned (although I am not entirely sure if Cosmos II is misaligned):
![image](https://user-images.githubusercontent.com/19388042/100999467-1b3ac880-355d-11eb-951b-64996266e961.png)
* I am not sure if the Trimaker printers will be sold outside of Argentina, but I would suggest to name the quality profiles using English words
* The size of Trimerk Nebula is set to 220x220x260 in Cura, while the [Trimaker Nebula page](https://trimaker.com/nebula/) says it is 230x230x260. Which one is the correct one?

2020-12-03 13:07 UTC, konskarm requested changes
Minor fixes. Grid has to be in single quotes as it is a value and not a setting name, or else Cura is searching for a setting called grid.

2020-12-03 13:07 UTC, konskarm commented on resources/definitions/trimaker_nebula.def.json
> +        "infill_pattern": {"value": "grid"},
```suggestion
        "infill_pattern": {"value": "'grid'"},
```

2020-12-03 13:07 UTC, konskarm commented on resources/definitions/trimaker_cosmosII.def.json
> +        "infill_pattern": {"value": "grid"},
```suggestion
        "infill_pattern": {"value": "'grid'"},
```

2021-01-04 12:43 UTC, tomasbaldi commented
Thank you very much @konskarm ! I really appreciate the work they do with CURA. I have made the changes you mentioned to me. The COSMOS printing area is offset from the center of the platform. The NEBULA's print area was wrong within the code. Thank you very much again!

2021-02-05 13:11 UTC, tomasbaldi commented
Hello! Are the changes I made correct?

2021-02-09 14:27 UTC, konskarm commented
Hi @tomasbaldi. Sorry for the long delay, this PR was lost among others. Everything seems to be working as expected now. The only issue I see is the mix of tabs and spaces in the .def.json files, but I will just fix it locally, no need to go back and forth. So I am merging this PR. The Trimaker printers will become available in the next Cura release.

2021-02-09 14:28 UTC, merged