Adding the MINGDA D2
Ultimaker/Cura pull request #8872
Opened 2020-12-02 11:32 UTC by cataclism

Hi! Cataclism here! I've worked in order to add the MINGDA D2 to Cura. The base is currently missing but i'll add it soon =)

2020-12-02 14:54 UTC, nallath commented
I'm a bit confused by the commit history of this PR. Why does it make all kinds of changes to the artillery_base?

2020-12-02 14:58 UTC, cataclism commented
@nallath i don't know why all the history of changes I made in the past are attacched to the PR. Only the last point of the list is the one of interest, all the previous are from my work for the Artillery printers and it has already been approved

2020-12-02 15:00 UTC, cataclism commented
I don't know how to remove it, if you can tell me how to, i'll do it @nallath

2020-12-03 16:15 UTC, Ghostkeeper commented
We can squash the commits when merging this.

You can also squash the commits yourself if you'd like to help. There are some instructions [online](https://gitbetter.substack.com/p/how-to-squash-git-commits). The basic idea is to do `git rebase -i master` while on your branch, which comes up with a file editor where you can say which commits need to be squashed into the previous commit. Then afterwards you'd need to force-push.

2020-12-03 16:22 UTC, Ghostkeeper commented
If the profiles for these printers are the same as the Artillery printers, I'd like to propose a change to set the following metadata on all of the new printers:

    "quality_definition": "artillery_base"

This tells Cura that you're using the Artillery's profiles. This has three consequences:

* If the Artillery profiles get updated, Mingda profiles will get updated too. This could be good (you get improvements made by the Artillery users as well) or bad (those improvements don't necessarily apply to your printer in some cases, although it might apply in many cases).
* You can then delete these quality profiles. Cura won't need to read these extra ~80 files at every launch, which will save an extra I/O block or two to read from disk.
* Material profiles that apply to Artillery printers will also apply to Mingda. This is something that is currently missing from your PR I think.

You can still override settings in the definition files and nozzle files, but you'd share the quality and material profiles with Artillery then.

2020-12-04 14:13 UTC, cataclism commented
I'll try to squash, hope i can do it! 
I'd like to keep them separate since they are different machines. I'll work on it

2020-12-08 11:03 UTC, Ghostkeeper commented
> I'd like to keep them separate since they are different machines.

I'd like to deduplicate them if their profiles are the same. If they need to be different that's fine, but if they might be different in the future we can always split the profiles then and deduplicate it now.

2020-12-15 13:16 UTC, cataclism commented
Ok @Ghostkeeper , got it. I'm working with the community in order to make the transition to the profiles as smooth as possible. So  changhes are coming in the next days

2021-01-02 11:47 UTC, cataclism commented
@Ghostkeeper  first of all happy new year!!
I've talked with the community and the profiles must be separated. 
So If there aren't any problems, you can merge.

2021-01-08 13:56 UTC, konskarm requested changes

2021-01-08 13:56 UTC, konskarm commented on resources/definitions/mingda_d2.def.json
> +		"platform": "mingda_d2_base.stl",
```suggestion
        "platform": "mingda_d2_base.stl",
```
Use spaces only, not tabs

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.3_PETG_standard.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.3_PETG_super.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.4_PETG_adaptive.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.4_PETG_low.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.4_PETG_standard.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.4_PETG_super.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.5_PETG_adaptive.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.5_PETG_low.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.5_PETG_standard.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.5_PETG_super.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.6_PETG_standard.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_0.8_PETG_draft.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/quality/mingda/PETG/mingda_1.0_PETG_draft.inst.cfg
> +#retraction_extra_prime_amount = 0.5
Remove comment

```suggestion
```

2021-01-08 13:56 UTC, konskarm commented on resources/definitions/mingda_base.def.json
> +        "retraction_hop_enabled": { "value": "true" },
```suggestion
        "retraction_hop_enabled": { "value": true },
```
`true` or `"True"` works, but not `"true"`.

2021-01-08 13:56 UTC, konskarm commented on resources/definitions/mingda_base.def.json
> +        "optimize_wall_printing_order": { "value": "True" },
```suggestion
        "optimize_wall_printing_order": { "value": true },
```
`"True"` will work, but it's better to use `true` instead.

2021-01-08 13:56 UTC, konskarm commented on resources/definitions/mingda_base.def.json
> +        "travel_compensate_overlapping_walls_0_enabled": { "value": "False" },
```suggestion
        "travel_compensate_overlapping_walls_0_enabled": { "value": false },
```
`"False"` will work, but it's better to use `false` instead.

2021-01-08 14:23 UTC, cataclism reviewed
Hope I did everything right! If there are any problems tell me @konskarm

2021-01-11 08:07 UTC, konskarm commented
Alright, since it is decided that the MINGDA definition should be completely separate from the Artillery ones, I will accept this PR. Just make sure to re-use the mingda_base, or else we are adding 88 files for a single printer, which is a bit excessive.

2021-01-11 08:07 UTC, merged