Added Maker Made 300x Printer
Ultimaker/Cura pull request #8901
Opened 2020-12-07 20:00 UTC by skilescm

2021-01-08 11:40 UTC, konskarm requested changes

2021-01-08 11:40 UTC, konskarm commented on resources/extruders/maker_made_300x_extruder_0.json
> +{
The extruder file should end in ".def.json".

2021-01-08 11:40 UTC, konskarm commented on resources/definitions/maker_made_300x.def.json
> +        "has_machine_quality": true,
As stated in https://github.com/Ultimaker/Cura/wiki/Definition-Files-Explained, the "has_machine_quality" should be set to true only if you have defined machine-specific quality files in the `resourses/quality/<machine_name>` folder.

2021-01-08 12:19 UTC, konskarm commented on resources/definitions/maker_made_300x.def.json
> +        "has_machine_materials": true,
```suggestion
```
No longer used.

2021-01-08 17:35 UTC, skilescm reviewed
All requested changes have been made.

2021-01-08 17:35 UTC, skilescm commented on resources/definitions/maker_made_300x.def.json
> +        "material_diameter": {"default_value": 1.75},
Deleted line 77

2021-01-08 17:38 UTC, skilescm commented
All requests fulfilled.

2021-01-11 08:14 UTC, konskarm commented
All issues have been fixed. The printer is added in Cura and slices without a problem. 
The Maker Made 300x definition will become available to be used in the next Cura release.

2021-01-11 08:15 UTC, merged