CURA-7868: Introduce the file provider plugin type
Ultimaker/Cura pull request #9012
Opened 2020-12-24 08:32 UTC by konskarm

CURA-7868

2020-12-29 14:13 UTC, Ghostkeeper requested changes

2021-01-04 14:12 UTC, konskarm commented on resources/qml/Menus/FileMenu.qml
> +            openFilesMenu.visible = (CuraApplication.getFileProviderModel().count > 1)
Your suspicion was correct! After using a variable for the model, the bindings were created automatically without the need for a Connection. Good catch!

Fixed in https://github.com/Ultimaker/Cura/pull/9012/commits/70550594cd113bee4af662c1dd980738ed3dbe0d.

2021-01-11 13:28 UTC, jellespijker requested changes
Couple of minor changes

2021-01-11 13:28 UTC, jellespijker commented on resources/qml/TableView.qml
> +import QtQuick 2.10
Latest supported QtQuick for Qt5.10 is 2.7

2021-01-11 17:22 UTC, jellespijker approved these changes

2021-01-11 17:24 UTC, jellespijker commented on resources/qml/TableView.qml
> +import QtQuick 2.10
Due to conflicting documentation on the Qt website, we will leave it as is and see how our build system handles this version

2021-01-11 17:24 UTC, merged