PostProcessingPlugin FilamentChange added Marlin Advanced Pause Feature!
Ultimaker/Cura pull request #9014
Opened 2020-12-24 08:50 UTC by Sekisback

with this modification, the plugin can use M600 from MarlinFW

2021-04-15 08:51 UTC, Ghostkeeper requested changes

2021-04-15 08:51 UTC, Ghostkeeper commented on plugins/PostProcessingPlugin/scripts/FilamentChange.py
> +            color_change = color_change + " ; Generated by FilamentChange plugin\n"
Might as well just unindent this line and remove the `if` case of the if-else clause. They are (and should stay) the same. And this one has no whitespace at the end of the line.

2021-04-15 08:51 UTC, Ghostkeeper commented on plugins/PostProcessingPlugin/scripts/FilamentChange.py
> +                    "default_value": true
We don't want to default to `true` here. Existing FilamentChange users would see their Filament Change settings suddenly not working any more. It's also good to give this more time in the field before it gets to be the default. Not everyone has the feature in their printer either.

2021-04-15 08:51 UTC, Ghostkeeper commented on plugins/PostProcessingPlugin/scripts/FilamentChange.py
> +                    "description": "Use configuration from Marlin Advanced Pause Feature!",
We should use a more... neutral tone.
```suggestion
                    "description": "Use configuration from Marlin's Advanced Pause Feature.",
```

2021-04-15 08:55 UTC, Ghostkeeper commented
These are things that I could fix myself pretty easily, but I'll let you fix them first if you like. The feature itself would be nice for many people.

2021-04-17 05:51 UTC, Sekisback commented
please feel free to change/fix these things to your needs, glad i could help

2021-05-05 12:54 UTC, merged

2021-05-05 12:55 UTC, Ghostkeeper commented
I changed the three things that I remarked about myself. Thanks for the contribution!