Adding Twotrees Full range printer profiles
Ultimaker/Cura pull request #9114
Opened 2021-01-12 04:04 UTC by Lester3DGadgets

Profile for:
Bluer / Bluer Plus / Sapphire Pro / Sapphire Plus

Nozzle size : 0.2mm to 1mm

Material: PLA / ABS / PETG / TPU

2021-01-12 04:16 UTC, Lester3DGadgets commented
Wondering why keep failing on check

2021-02-22 08:31 UTC, konskarm commented
Thanks for your PR @Lester3DGadgets. 

One thing I notice, the Two Trees Bluer machine definition already exist in our codebase. It was added in PR https://github.com/Ultimaker/Cura/pull/8620. In addition, there is another PR before yours (https://github.com/Ultimaker/Cura/pull/9102) that is attempting to add the Two Trees Sapphire Pro definition. I would like to request from you to contact @WashingtonJunior and @G4Cab and make sure they are ok with you overridding their machine profiles. If they are fine with it, just make sure you also remove those old profiles as part of your PR.

**Note:** If it is decided that your TwoTrees Bluer will override the old one, we need to add it to our version upgrade script, since the name of the printer definition file is not the same (`twotrees_bluer.def.json` (old) vs `two_trees_bluer.def.json`(new)). This will be done on our side, but I am mentioning it here so that we don't forget.

2021-02-23 02:34 UTC, Lester3DGadgets commented
Hello @WashingtonJunior @G4Cab,

Can we standardize and use the profile that i created? It structured base profile and included all twotrees models such as Bluer, Bluer Plus, Sapphire Pro and Saspphire. On top of that the profile also included few qualities selection with a few material like PLA, ABS, PETG and TPU.

2021-03-04 09:01 UTC, konskarm commented
Let's wait for a week or so and if there is no response, I'll go forward with yours.

2021-03-05 12:02 UTC, G4Cab commented
Sure, do what you need to do, i only created this profile, cause it didn't existed

2021-03-05 13:01 UTC, konskarm commented
Thanks for your response @G4Cab. I just needed confirmation. I'll go forward and close your other two PRs https://github.com/Ultimaker/Cura/pull/9102 and https://github.com/Ultimaker/Cura/pull/9132, and will continue with this one.

2021-03-05 17:11 UTC, konskarm requested changes
Just a few code-style changes:

- There is a mix of tabs and spaces. I highlighted all of them so that it is easy for you to find and change.
- Please rename `resources/meshes/sapphireplus_platform.stl` to `resources/meshes/two_trees_sapphireplus_platform.stl` and `resources/meshes/sapphireplus_platform.stl` to `resources/meshes/two_trees_sapphireplus_platform.stl`. It will be easier to understand to which printers they refer to.

I also noticed that the stl files seem to be empty, but once I try to download them they are properly filled, so this is probably a bug on GitHub's side.

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_base.def.json
> +		"retraction_speed": { "default_value" : 40 },
```suggestion
        "retraction_speed": { "default_value" : 40 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_base.def.json
> +		"cool_fan_full_layer": { "value": "2" },
```suggestion
        "cool_fan_full_layer": { "value": "2" },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluer.def.json
> +		"machine_start_gcode": { "default_value": "G28 ;Home\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move bed down\nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position\nG1 X10.1 Y200.0 Z0.28 F1500.0 E15 ;Dr
```suggestion
        "machine_start_gcode": { "default_value": "G28 ;Home\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move bed down\nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position\nG1 X10.1 Y200.0 Z0.28 F1500.0 E15 ;Draw the first line\nG1 X10.4 Y200.0 Z0.28 F5000.0 ;Move to side a little\nG1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move Bed up" },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluer.def.json
> +		},
```suggestion
        [-47, 37],
        [-47, -23],
        [47, -23],
        [47, 37]
        ]
        },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluer.def.json
> +		"retraction_speed": { "default_value" : 50 },
```suggestion
        "speed_print": { "value": 50.0 },
        "speed_travel": { "value": 180 },
        "speed_travel_layer_0": { "value": 100 },
        "retraction_speed": { "default_value" : 50 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluer.def.json
> +		"infill_overlap": { "value": 30 },
```suggestion
        "material_flow": { "value": 90 },
        "infill_material_flow": { "value": 100 },
        
        "infill_overlap": { "value": 30 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluer.def.json
> +		"platform": "twotrees235x235_generic.stl"
```suggestion
        "platform": "twotrees235x235_generic.stl"
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluerplus.def.json
> +		},
```suggestion
        [-47, 37],
        [-47, -23],
        [47, -23],
        [47, 37]
        ]
        },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluerplus.def.json
> +		"retraction_speed": { "default_value" : 50 },
```suggestion
        "speed_print": { "value": 50.0 },
        "speed_travel": { "value": 180 },
        "speed_travel_layer_0": { "value": 100 },
        "retraction_speed": { "default_value" : 50 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluerplus.def.json
> +		"infill_overlap": { "value": 30 },
```suggestion
        "material_flow": { "value": 90 },
        "infill_material_flow": { "value": 100 },
        
        "infill_overlap": { "value": 30 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_bluerplus.def.json
> +		"platform": "twotrees300x300_generic.stl"
```suggestion
        "platform": "twotrees300x300_generic.stl"
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphireplus.def.json
> +		},
```suggestion
        [-30,19],
        [30,19],
        [30,-49],
        [-30,-49]
        ] 
        },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphireplus.def.json
> +		"retraction_speed": { "default_value" : 40 },
```suggestion
        "speed_travel": { "value": 180 },
        "speed_travel_layer_0": { "value": 100 },
        "retraction_speed": { "default_value" : 40 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphireplus.def.json
> +		"infill_overlap": { "value": 30 },
```suggestion
        "material_flow": { "value": 90 },
        "infill_material_flow": { "value": 100 },
        
        "infill_overlap": { "value": 30 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphireplus.def.json
> +
```suggestion
        "platform": "sapphireplus_platform.stl"
        
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphirepro.def.json
> +	    "machine_start_gcode": { "default_value": "G28 ;Home\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move bed down\nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position\nG1 X10.1 Y200.0 Z0.28 F1500.0 E15
```suggestion
        "machine_start_gcode": { "default_value": "G28 ;Home\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move bed down\nG1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position\nG1 X10.1 Y200.0 Z0.28 F1500.0 E15 ;Draw the first line\nG1 X10.4 Y200.0 Z0.28 F5000.0 ;Move to side a little\nG1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line\nG92 E0 ;Reset Extruder\nG1 Z2.0 F3000 ;Move Bed up" },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphirepro.def.json
> +
```suggestion
        [-30,19],
        [30,19],
        [30,-49],
        [-30,-49]
        ] 
        },

```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphirepro.def.json
> +		"retraction_speed": { "default_value" : 40 },
```suggestion
        "speed_travel": { "value": 180 },
        "speed_travel_layer_0": { "value": 100 },
        "retraction_speed": { "default_value" : 40 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphirepro.def.json
> +		"infill_overlap": { "value": 30 },
```suggestion
        "material_flow": { "value": 90 },
        "infill_material_flow": { "value": 100 },
        
        "infill_overlap": { "value": 30 },
```

2021-03-05 17:11 UTC, konskarm commented on resources/definitions/two_trees_sapphirepro.def.json
> +		"platform": "sapphirepro_platform.stl"
```suggestion
        "platform": "sapphirepro_platform.stl"
```

2021-03-07 02:43 UTC, Lester3DGadgets commented
updated all the code as per suggestion. Thanks guys.

2021-04-16 15:41 UTC, MarioGK commented
Any idea when this might be merged?

2021-04-21 08:03 UTC, Lester3DGadgets commented
Cura 4.9 released, unfortunately this full list of profile are not being merged  yet.

2021-04-24 11:56 UTC, MarioGK commented
@Lester3DGadgets Thank you for the hard work, the profiles are working beautifully for me, i am using your fork for now i hope Cura maintainers could merge it soon so it would be easier, btw it seems that you have a duplicate printer in there, on the menu to add a printer there's "Two Trees" and "TwoTrees"

2021-05-04 13:06 UTC, Ghostkeeper commented
Yes, the TwoTrees Bluer printer is duplicating the one added in November: https://github.com/Ultimaker/Cura/pull/8620

2021-05-04 13:15 UTC, Ghostkeeper requested changes
Indeed, the Two Trees Bluer printer duplicates the one added in November: https://github.com/Ultimaker/Cura/pull/8620

The previous review caught most issues already, but it wasn't noticed then that this would be duplicate.

Developers, this feature is tracked in our tracker as CURA-8212.

2021-05-04 13:15 UTC, Ghostkeeper commented on resources/definitions/two_trees_bluer.def.json
> +    "name": "Two Trees Bluer",
This profile duplicates the TwoTrees Bluer printer already added to Cura. Could you update the existing definition instead? Changing the definition ID would require a version upgrade.

2021-05-04 14:53 UTC, Ghostkeeper commented
I'm told that another developer has been working on a version upgrade to help transition users of the existing Bluer profile to your new ones. This is necessary anyway because your new one has different default profiles.

2021-05-10 15:23 UTC, merged

2021-05-10 15:54 UTC, konskarm commented
Related version upgrader PR: https://github.com/Ultimaker/Cura/pull/9805.