Update ideagen3D_sapphire_plus.def.json
Ultimaker/Cura pull request #9213
Opened 2021-01-31 14:50 UTC by Firedrops

Added Restore Bed Levelling after Homing to start G-Code.

2021-02-08 12:22 UTC, Ghostkeeper requested changes

2021-02-08 12:22 UTC, Ghostkeeper commented on resources/definitions/ideagen3D_sapphire_plus.def.json
> +    "version": 3,
This is a version number of the file format, and should be left at 2 since it's the most recent version.

```suggestion
    "version": 2,
```

2021-02-26 13:58 UTC, konskarm commented on resources/definitions/ideagen3D_sapphire_plus.def.json
> +    "version": 3,
Although @Ghostkeeper's comment was originally resolved, the version is now again changed to 3. Please change it back to 2 and the tests won't fail.


```suggestion
    "version": 2,
```

2021-03-02 14:12 UTC, konskarm approved these changes

2021-03-02 14:23 UTC, merged