Add new printer to Ultimaker Cura
Ultimaker/Cura pull request #9340
Opened 2021-02-27 09:41 UTC by mixware011

Hello Team Cura,

We've developed a new FDM 3D printer, named Mixware Hyper-S.

We wants to add our printer profile definition i.e. Mixware Hyper-S in ultimaker Cura slicer.

2021-03-01 12:57 UTC, nallath commented
The STL you provided is empty.

2021-05-03 14:01 UTC, nallath requested changes
I've looked at a random sample of your settings and pretty much all of them are re-defined in some form or another. 

It will make it a lot easier to maintain if you don't re-define settings like that. 

Please go over the provided settings once more and check if it's actually needed to change them.

2021-05-29 08:35 UTC, mixware011 commented on resources/quality/mixware_hyper_s/mixware_hyper_s_normal.inst.cfg
> +acceleration_enabled = True
I hadn't thought about easier maintenance.
Now I resubmit.

2021-05-29 08:35 UTC, mixware011 commented on resources/quality/mixware_hyper_s/mixware_hyper_s_normal.inst.cfg
> +infill_before_walls = False
I hadn't thought about easier maintenance.
Now I resubmit.

2021-05-29 08:35 UTC, mixware011 commented on resources/quality/mixware_hyper_s/mixware_hyper_s_normal.inst.cfg
> +jerk_enabled = True
I hadn't thought about easier maintenance.
Now I resubmit.

2021-05-29 08:36 UTC, mixware011 commented on resources/quality/mixware_hyper_s/mixware_hyper_s_normal.inst.cfg
> +support_enable = True
I hadn't thought about easier maintenance.
Now I resubmit.

2021-07-01 15:01 UTC, konskarm requested changes

2021-12-17 14:21 UTC, Ghostkeeper approved these changes
Aside from that there were apparently different setting values previously, the current setting values look good to me.

This PR kind of got lost due to not having taken off the "needs info" label, because the issue with the platform adhesion and jerk was never addressed. But you seem to be maintaining it still and so we'll assume that it prints correctly.

I'll update the `setting_version`, give these profiles a test and we can then maybe finally merge them into mainline Cura.

2021-12-17 14:45 UTC, merged

2021-12-17 14:48 UTC, Ghostkeeper commented
I fixed up the tests that were failing. No idea why Github thinks there were 2000 commits in this PR though. There were only 50. It's got to do with the push I did to the upstream repository I think, but that push contains only commits from mainline Cura.

One point of concern is that you probably intended this to come along with some Mixware material profiles, but those profiles are not submitted to the fdm_materials repository. I changed it to default to generic_pla instead.