Add flow rate to simulation view
Ultimaker/Cura pull request #9410
Opened 2021-03-17 02:13 UTC by khani3s

WIP

Add Flow rate to simulation view

Flow Rate (AKA volumetric flow rate, volume flow rate, rate of fluid flow, volume velocity or volumetric speed) is used defined on 3dp as `line width * thickness * feedrate`. The unit is mm³/s

Is useful to check if your printing inside your hot end/extruder limits.

This implementation is based on #9289 and does not take into account (I think) material_flow.

TODO

- [ ] Define the name of the view
- [ ] Add to I18n
- [ ] Build
- [ ] Test

2021-03-17 09:18 UTC, nallath commented
Oh, you don't need to make the actual appimage. I just test Cura when running it from source. In 99% of the cases running it from source is the same as the appimage / binary. 

In the few cases that it isn't, we have a automatic build system that spits out nightlies and which gets used & tested by our QA engineers.

2021-04-29 12:48 UTC, jellespijker commented
Hi @khani3s I was wondering if you're still stuck and if that is the case how I could help you. I kinda like what you're doing here, sot it would be great if we could merge it.

2021-04-29 15:54 UTC, jellespijker requested changes
I think you're almost there. If you implement the following fixes in the code, you should have something working. See the image below.

I would suggest that you name it `Flow rate` instead of `Flow` and it might be a good idea to merge master into your own branch again since there were many changes in between your PR and now.

Don't worry about setting up the complete build environment, if it runs from source it will most likely run in our builds as well and we have the automatic tests to catch errors as well.

![image](https://user-images.githubusercontent.com/8535734/116579927-2d097780-a913-11eb-8d6c-e9c84ec519b1.png)

2021-04-29 15:54 UTC, jellespijker commented on plugins/SimulationView/layers3d.shader
> +        a_flow_rate =  a_line_dim.x * a_line_dim.y * a_feedrate
missing `;`

2021-04-29 15:54 UTC, jellespijker commented on plugins/SimulationView/layers3d.shader
> +        a_flow_rate =  a_line_dim.x * a_line_dim.y * a_feedrate
and trying to write to a read only variable. See comment below

2021-04-29 15:54 UTC, jellespijker commented on plugins/SimulationView/layers3d.shader
> +                v_color = flowRateGradientColor(a_flow_rate, u_min_flow_rate, u_max_flow_rate);
Calculate flow here.
```
            case 5:  // "Flow rate"
                float flow_rate =  a_line_dim.x * a_line_dim.y * a_feedrate;
                v_color = flowRateGradientColor(flow_rate, u_min_flow_rate, u_max_flow_rate);
                break;
```

2021-04-29 15:54 UTC, jellespijker commented on plugins/SimulationView/layers3d.shader
> +    in highp float a_flow_rate;
Not needed, see comments below

2021-05-09 06:34 UTC, khani3s commented
I am still stucked trying to run from source. I installed a fresh ubuntu 20.04 and make some progress...
Now I am stuck at

```
python3 cura_app.py
/usr/lib/python3/dist-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/usr/lib/python3/dist-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/home/felipe/3dp/cura2/Uranium/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[MainThread] UM.Application.initialize [160]: Initializing Ultimaker Cura
[MainThread] UM.Application.initialize [161]: App Version master
[MainThread] UM.Application.initialize [162]: Api Version 7.5.0
[MainThread] UM.Application.initialize [163]: Build type None
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /usr/bin/share/uranium/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /usr/bin/share/cura/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib64/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib32/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /usr/bin/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/Resources/uranium/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/Resources/cura/plugins must be a folder.
[MainThread] UM.Resources.__initializeStoragePaths [446]: Initializing storage paths
[MainThread] UM.Resources.__initializeStoragePaths [456]: Config storage path is /home/felipe/.config/cura/master
[MainThread] UM.Resources.__initializeStoragePaths [464]: Data storage path is /home/felipe/.local/share/cura/master
[MainThread] UM.Resources.__initializeStoragePaths [476]: Cache storage path is /home/felipe/.cache/cura/master
[MainThread] UM.PackageManager.__init__ [55]: Found bundled packages JSON file: /home/felipe/3dp/cura2/Uranium/UM/../resources/bundled_packages/uranium.json
[MainThread] UM.PackageManager.__init__ [55]: Found bundled packages JSON file: /media/felipe/Backup/backup/3dp/cura2/Cura/cura/../resources/bundled_packages/cura.json
[MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [118]: Trying OpenGL context 4.1...
[MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [126]: Yay, we got at least OpenGL 4.1 core: 4.5 Core profile
[MainThread] UM.Qt.QtApplication.initialize [175]: Detected most suitable OpenGL context version: 4.1 Core profile
[MainThread] UM.Qt.QtApplication.initialize [182]: Initializing job queue ...
[MainThread] UM.Qt.QtApplication.initialize [186]: Initializing version upgrade manager ...
[MainThread] UM.PackageManager._loadManagementData [169]: Loaded bundled packages data from /home/felipe/3dp/cura2/Uranium/UM/../resources/bundled_packages/uranium.json
[MainThread] UM.PackageManager._loadManagementData [169]: Loaded bundled packages data from /media/felipe/Backup/backup/3dp/cura2/Cura/cura/../resources/bundled_packages/cura.json
[MainThread] UM.PackageManager._loadManagementData [196]: Loaded user packages management file from /home/felipe/.local/share/cura/master/packages.json
[MainThread] UM.PackageManager._saveManagementData [269]: Package management file /home/felipe/.local/share/cura/master/packages.json was saved
/media/felipe/Backup/backup/3dp/cura2/Cura/cura/UI/CuraSplashScreen.py:73: DeprecationWarning: an integer is required (got type Alignment).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  painter.drawText(60, 70 + self._version_y_offset, round(330 * self._scale), round(230 * self._scale), Qt.AlignLeft | Qt.AlignTop, version[0])
[MainThread] UM.PluginRegistry.initializeBeforePluginsAreLoaded [117]: Loading plugin configuration file '/home/felipe/.config/cura/master/plugins.json'
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib64/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/libx32/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [205]: Plugin location /media/felipe/Backup/backup/3dp/cura2/lib32/cura must be a folder.
2021-05-09 03:33:10,067 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin ConsoleLogger
2021-05-09 03:33:10,071 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin LocalFileOutputDevice
2021-05-09 03:33:10,073 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin OBJReader
2021-05-09 03:33:10,077 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin OBJWriter
2021-05-09 03:33:10,079 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin STLWriter
2021-05-09 03:33:10,082 - WARNING - [MainThread] STLReader.STLReader.<module> [31]: Not loading numpy-stl due to linux issue
2021-05-09 03:33:10,084 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin STLReader
2021-05-09 03:33:10,087 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin FileLogger
2021-05-09 03:33:10,089 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin LocalContainerProvider
2021-05-09 03:33:10,091 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin SelectionTool
2021-05-09 03:33:10,095 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin ScaleTool
2021-05-09 03:33:10,097 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin CameraTool
2021-05-09 03:33:10,100 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin TranslateTool
2021-05-09 03:33:10,104 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin RotateTool
2021-05-09 03:33:10,107 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin MirrorTool
2021-05-09 03:33:10,112 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin UpdateChecker
2021-05-09 03:33:10,116 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin SimpleView
2021-05-09 03:33:10,128 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin X3DReader
2021-05-09 03:33:10,129 - INFO - [JobQueueWorker [0]] UpdateChecker.UpdateCheckerJob.run [40]: Checking for new version of cura
2021-05-09 03:33:10,142 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin GCodeReader
2021-05-09 03:33:10,148 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin PostProcessingPlugin
2021-05-09 03:33:10,152 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [470]: Loaded plugin VersionUpgrade47to48
2021-05-09 0 [...]

2021-05-09 10:35 UTC, fieldOfView commented
I think you stumbled across a "typo" or mistake. According to the [qtquick documentation](https://doc.qt.io/archives/qt-5.11/qtquickcontrols2-index.html#versions), module "QtQuick.Controls" version 2.11 does not exist yet, and the file should actually be using module "QtQuick.Controls" version 2.4. It is interesting though that you are the first to stumble into this as something that stops Cura from loading.

2021-05-09 10:49 UTC, fieldOfView commented
I have created https://github.com/Ultimaker/Cura/pull/9799 to fix the version issue.

2021-05-09 14:10 UTC, khani3s commented
I was using the Qt recommended here:

https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Ubuntu

PyQt5==5.10

The requirements.txt version solved the problem:

PyQt5==5.15.2

2021-05-10 04:05 UTC, khani3s commented
> Btw it looks like something is a bit off with the max flow rate calculation. A flow of 26 mm3/s is very high

I notice that too. And after debugging I think that is related to the "Fill Gaps lines". 
If you set "Fill Gaps Between Walls" to "Nowhere" the flow goes it a normal range. 
On another model I found a single point with a high value on the gaps.

2021-05-10 04:06 UTC, khani3s commented on plugins/SimulationView/SimulationView.py
> +        min_flow_rate = self._min_line_width * self._min_thickness * self.min_feedrate
done

2021-05-10 04:09 UTC, khani3s commented
![Screenshot from 2021-05-10 00-34-04](https://user-images.githubusercontent.com/152649/117604655-52c12880-b12c-11eb-8a02-dce66f7e98b4.png)

2021-05-10 09:38 UTC, nallath commented
> I was using the Qt recommended here:
> 
> https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Ubuntu
> 
> PyQt5==5.10
> 
> The requirements.txt version solved the problem:
> 
> PyQt5==5.15.2

Whoops. I've updated the documentation.

2021-05-10 11:54 UTC, nallath commented
I've managed to get a bit of a weird result

![image](https://user-images.githubusercontent.com/3922611/117655286-268ec180-b197-11eb-8df8-edc3f327d40f.png)

My guess is that it's caused by the min & the max being the same.

2021-05-10 12:06 UTC, khani3s commented
@nallath could you send me that project?

2021-05-10 12:22 UTC, nallath commented
[UMS3_tetrahedron.zip](https://github.com/Ultimaker/Cura/files/6451930/UMS3_tetrahedron.zip)

The issue only occurs if you only show the helpers.

2021-05-13 21:30 UTC, Ghostkeeper requested changes
Oh, I think that visualisation bug is because of this recently merged pull request: https://github.com/Ultimaker/Cura/pull/9498

2021-05-13 21:30 UTC, Ghostkeeper commented on plugins/SimulationView/layers3d.shader
> +      float t = 2.0 * ((abs_value - min_value) / (max_value - min_value)) - 1;
To fix it, you'll need to change this line to something like:

```suggestion
      float t;
      if(abs(min_value - max_value) < 0.001)
      {
          t = 0;
      }
      else
      {
          t = 2.0 * ((abs_value - min_value) / (max_value - min_value)) - 1;
      }
```

2021-05-17 08:39 UTC, nallath commented
The fix suggested by @Ghostkeeper fixes it, so i've merged this! 

Github is however not quite understanding that :S ( But fear not; it is in the next release!)

2021-05-17 08:39 UTC, closed without merging