Add Z Position parameter to FilamentChange
Ultimaker/Cura pull request #9658
Opened 2021-04-22 16:34 UTC by Humsie

This PR will add a `Z position` parameter to the FilamentChange script (PostProcessingPlugin) so you can control all 3 coordinates where the printhead will park while performing the filament change.

Usefull if you have a low print and need room to extrude the old filament for example. 

Tested on Ender 3 (+octoprint)

2021-05-14 09:54 UTC, konskarm requested changes
Just a small change. Even though you already filter against negative values, you can set the minimum value to 0 so that there is an indication in the interface

![image](https://user-images.githubusercontent.com/19388042/118254091-fe5ed580-b4aa-11eb-984b-00edee9b0910.png)

2021-05-14 09:54 UTC, konskarm commented on plugins/PostProcessingPlugin/scripts/FilamentChange.py
> +                    "default_value": 0
```suggestion
                    "default_value": 0,
                    "minimum_valiue": 0
```

2021-05-19 16:22 UTC, Humsie commented on plugins/PostProcessingPlugin/scripts/FilamentChange.py
> +                    "default_value": 0
Added the minimum value parameter.

2021-05-21 15:02 UTC, konskarm approved these changes

2021-05-21 15:02 UTC, merged