Adding New Machines to Cura
Ultimaker/Cura pull request #9863
Opened 2021-05-18 04:35 UTC by v27jain

2021-06-22 15:41 UTC, konskarm requested changes
Since the 3DI D300 and D220 are almost identical (only the `name`, `platform`, `platform_offset`, and the machine sizes are different), please consider creating a `3di_base.def.json` and in the `3di_d300.def.json` and `3di_d220.def.json` inherit from the `3di_base`. This way, you don't even need to have two different extruders. You can have a single extruder (`3di_base_extruder_0.def.json`) assigned to the `3di_base`.

You can draw inspiration about the inheritance system from other printer families, such as the creality ones.

2021-07-13 15:49 UTC, konskarm requested changes
The json files cannot be decoded because of those commas, which also causes the failing tests. Once these are removed, the printers should work without issues.

2021-07-13 15:49 UTC, konskarm commented on resources/definitions/3di_d220.def.json
> +        "platform_offset": [0, -5, 0],
```suggestion
        "platform_offset": [0, -5, 0]

```

2021-07-13 15:49 UTC, konskarm commented on resources/definitions/3di_d220.def.json
> +        },
```suggestion
        }

```

2021-07-13 15:49 UTC, konskarm commented on resources/definitions/3di_d300.def.json
> +        "platform_offset": [-200, -5, 173.205],
```suggestion
        "platform_offset": [-200, -5, 173.205]

```

2021-07-13 15:49 UTC, konskarm commented on resources/definitions/3di_d300.def.json
> +        },
```suggestion
        }

```

2021-07-14 12:41 UTC, konskarm approved these changes

2021-07-14 14:01 UTC, konskarm requested changes
It seems that the buildplate is not aligned properly in the 3DI D300

![image](https://user-images.githubusercontent.com/19388042/125635234-040f4137-8398-4016-8074-ac40255d1740.png)

2021-07-14 14:49 UTC, v27jain commented
I had checked this in the very first upload. It showed the alignment correctly.
I haven't changed the bed.stl file and the bed offset value since the changes were requested. I will verify it again. Regards.

2021-08-30 14:30 UTC, konskarm commented
The platform is now perfectly aligned in the D300. I have just a small request. I cannot find anywhere a reference to the 3DI D220 printer. Could you point me to a page with its specifications? I wanted to ensure that the size is the correct one.

2021-08-30 14:31 UTC, konskarm approved these changes

2021-09-09 11:07 UTC, Ghostkeeper commented
Seems a bit like this D220 is not released yet, still a prototype printer, maybe? There's no trace of it to be found on the internet at least.

2021-09-09 17:15 UTC, v27jain commented
> Seems a bit like this D220 is not released yet, still a prototype printer, maybe? There's no trace of it to be found on the internet at least.

I was waiting for an update on our website. This is the previous version named Noisybot (Diameter 180, Height 250)

https://3deometry.com/3d-printers/3deometry/3di-noisybot/

D220 is an upgraded version of this with (Diameter 220, Height 250).
Will be updating Noisybot to D220 on our website soon.

2021-09-17 12:43 UTC, Ghostkeeper commented
We don't normally provide profiles for prototypes or other in-development or custom-built printers. I think we'll wait with this merge until that printer is at least released on the website.

2021-10-04 06:09 UTC, v27jain commented
> We don't normally distribute profiles for prototypes or other in-development or custom-built printers. I think we'll wait with this merge until that printer is at least released on the website.

Okay, I will remove the 3DI D220 version now. Will add once its released on our website.

2021-10-05 14:38 UTC, konskarm commented
Thanks for your response @v27jain. The printer 3DI 300 slices without issues so I am merging this. The 3DI D300 printer will show up in the available printers in Cura 4.12 onwards.

2021-10-05 14:38 UTC, merged